/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.orders.lines;

import com.paid.api.core.ClientOptions;
import com.paid.api.core.RequestOptions;
import com.paid.api.resources.orders.lines.requests.LinesUpdateRequest;
import com.paid.api.types.Order;
import java.util.concurrent.CompletableFuture;

public class AsyncLinesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawLinesClient rawClient;

    public AsyncLinesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawLinesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawLinesClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<Order> update(String orderId) {
        return this.rawClient.update(orderId).thenApply(response -> response.body());
    }

    public CompletableFuture<Order> update(String orderId, LinesUpdateRequest request) {
        return this.rawClient.update(orderId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Order> update(String orderId, LinesUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(orderId, request, requestOptions).thenApply(response -> response.body());
    }
}
