/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.credits.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCreditCurrencyRequest.Builder.class)
public final class CreateCreditCurrencyRequest {
    private final String name;

    private final String key;

    private final Optional<String> description;

    private final Map<String, Object> additionalProperties;

    private CreateCreditCurrencyRequest(
            String name, String key, Optional<String> description, Map<String, Object> additionalProperties) {
        this.name = name;
        this.key = key;
        this.description = description;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Human-readable name shown for this credit currency.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Stable machine-readable key for this credit currency. Use lowercase letters, numbers, underscores, and hyphens. Keys are unique within an organization.
     */
    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    /**
     * @return Optional description for this credit currency.
     */
    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateCreditCurrencyRequest && equalTo((CreateCreditCurrencyRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateCreditCurrencyRequest other) {
        return name.equals(other.name) && key.equals(other.key) && description.equals(other.description);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.key, this.description);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Human-readable name shown for this credit currency.</p>
         */
        KeyStage name(@NotNull String name);

        Builder from(CreateCreditCurrencyRequest other);
    }

    public interface KeyStage {
        /**
         * <p>Stable machine-readable key for this credit currency. Use lowercase letters, numbers, underscores, and hyphens. Keys are unique within an organization.</p>
         */
        _FinalStage key(@NotNull String key);
    }

    public interface _FinalStage {
        CreateCreditCurrencyRequest build();

        /**
         * <p>Optional description for this credit currency.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, KeyStage, _FinalStage {
        private String name;

        private String key;

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateCreditCurrencyRequest other) {
            name(other.getName());
            key(other.getKey());
            description(other.getDescription());
            return this;
        }

        /**
         * <p>Human-readable name shown for this credit currency.</p>
         * <p>Human-readable name shown for this credit currency.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public KeyStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Stable machine-readable key for this credit currency. Use lowercase letters, numbers, underscores, and hyphens. Keys are unique within an organization.</p>
         * <p>Stable machine-readable key for this credit currency. Use lowercase letters, numbers, underscores, and hyphens. Keys are unique within an organization.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("key")
        public _FinalStage key(@NotNull String key) {
            this.key = Objects.requireNonNull(key, "key must not be null");
            return this;
        }

        /**
         * <p>Optional description for this credit currency.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        /**
         * <p>Optional description for this credit currency.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Optional description for this credit currency.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public CreateCreditCurrencyRequest build() {
            return new CreateCreditCurrencyRequest(name, key, description, additionalProperties);
        }
    }
}
