/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.credits.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import com.paid.api.resources.credits.types.ListCreditTransactionsRequestType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCreditTransactionsRequest.Builder.class)
public final class ListCreditTransactionsRequest {
    private final Optional<Integer> limit;

    private final Optional<Integer> offset;

    private final Optional<String> customerId;

    private final Optional<String> externalCustomerId;

    private final Optional<String> creditsCurrencyId;

    private final Optional<String> creditCurrencyKey;

    private final Optional<ListCreditTransactionsRequestType> type;

    private final Optional<String> orderId;

    private final Optional<String> eventName;

    private final Optional<String> createdAtFrom;

    private final Optional<String> createdAtTo;

    private final Map<String, Object> additionalProperties;

    private ListCreditTransactionsRequest(
            Optional<Integer> limit,
            Optional<Integer> offset,
            Optional<String> customerId,
            Optional<String> externalCustomerId,
            Optional<String> creditsCurrencyId,
            Optional<String> creditCurrencyKey,
            Optional<ListCreditTransactionsRequestType> type,
            Optional<String> orderId,
            Optional<String> eventName,
            Optional<String> createdAtFrom,
            Optional<String> createdAtTo,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.offset = offset;
        this.customerId = customerId;
        this.externalCustomerId = externalCustomerId;
        this.creditsCurrencyId = creditsCurrencyId;
        this.creditCurrencyKey = creditCurrencyKey;
        this.type = type;
        this.orderId = orderId;
        this.eventName = eventName;
        this.createdAtFrom = createdAtFrom;
        this.createdAtTo = createdAtTo;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @JsonProperty("offset")
    public Optional<Integer> getOffset() {
        return offset;
    }

    /**
     * @return Filter by customer ID.
     */
    @JsonProperty("customerId")
    public Optional<String> getCustomerId() {
        return customerId;
    }

    /**
     * @return Filter by customer external ID.
     */
    @JsonProperty("externalCustomerId")
    public Optional<String> getExternalCustomerId() {
        return externalCustomerId;
    }

    /**
     * @return Filter by credit currency ID.
     */
    @JsonProperty("creditsCurrencyId")
    public Optional<String> getCreditsCurrencyId() {
        return creditsCurrencyId;
    }

    /**
     * @return Filter by the stable machine-readable key of the credit currency.
     */
    @JsonProperty("creditCurrencyKey")
    public Optional<String> getCreditCurrencyKey() {
        return creditCurrencyKey;
    }

    /**
     * @return Filter by transaction type.
     */
    @JsonProperty("type")
    public Optional<ListCreditTransactionsRequestType> getType() {
        return type;
    }

    /**
     * @return Filter by the order this transaction is linked to.
     */
    @JsonProperty("orderId")
    public Optional<String> getOrderId() {
        return orderId;
    }

    /**
     * @return Filter by the usage event that produced the transaction (exact match, untrimmed). Transactions with no event (grants, invoice-void clawbacks, manual adjustments) never match.
     */
    @JsonProperty("eventName")
    public Optional<String> getEventName() {
        return eventName;
    }

    /**
     * @return Only transactions recorded on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.
     */
    @JsonProperty("createdAtFrom")
    public Optional<String> getCreatedAtFrom() {
        return createdAtFrom;
    }

    /**
     * @return Only transactions recorded on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.
     */
    @JsonProperty("createdAtTo")
    public Optional<String> getCreatedAtTo() {
        return createdAtTo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCreditTransactionsRequest && equalTo((ListCreditTransactionsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCreditTransactionsRequest other) {
        return limit.equals(other.limit)
                && offset.equals(other.offset)
                && customerId.equals(other.customerId)
                && externalCustomerId.equals(other.externalCustomerId)
                && creditsCurrencyId.equals(other.creditsCurrencyId)
                && creditCurrencyKey.equals(other.creditCurrencyKey)
                && type.equals(other.type)
                && orderId.equals(other.orderId)
                && eventName.equals(other.eventName)
                && createdAtFrom.equals(other.createdAtFrom)
                && createdAtTo.equals(other.createdAtTo);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.limit,
                this.offset,
                this.customerId,
                this.externalCustomerId,
                this.creditsCurrencyId,
                this.creditCurrencyKey,
                this.type,
                this.orderId,
                this.eventName,
                this.createdAtFrom,
                this.createdAtTo);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> offset = Optional.empty();

        private Optional<String> customerId = Optional.empty();

        private Optional<String> externalCustomerId = Optional.empty();

        private Optional<String> creditsCurrencyId = Optional.empty();

        private Optional<String> creditCurrencyKey = Optional.empty();

        private Optional<ListCreditTransactionsRequestType> type = Optional.empty();

        private Optional<String> orderId = Optional.empty();

        private Optional<String> eventName = Optional.empty();

        private Optional<String> createdAtFrom = Optional.empty();

        private Optional<String> createdAtTo = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCreditTransactionsRequest other) {
            limit(other.getLimit());
            offset(other.getOffset());
            customerId(other.getCustomerId());
            externalCustomerId(other.getExternalCustomerId());
            creditsCurrencyId(other.getCreditsCurrencyId());
            creditCurrencyKey(other.getCreditCurrencyKey());
            type(other.getType());
            orderId(other.getOrderId());
            eventName(other.getEventName());
            createdAtFrom(other.getCreatedAtFrom());
            createdAtTo(other.getCreatedAtTo());
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Integer> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Integer offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        /**
         * <p>Filter by customer ID.</p>
         */
        @JsonSetter(value = "customerId", nulls = Nulls.SKIP)
        public Builder customerId(Optional<String> customerId) {
            this.customerId = customerId;
            return this;
        }

        public Builder customerId(String customerId) {
            this.customerId = Optional.ofNullable(customerId);
            return this;
        }

        /**
         * <p>Filter by customer external ID.</p>
         */
        @JsonSetter(value = "externalCustomerId", nulls = Nulls.SKIP)
        public Builder externalCustomerId(Optional<String> externalCustomerId) {
            this.externalCustomerId = externalCustomerId;
            return this;
        }

        public Builder externalCustomerId(String externalCustomerId) {
            this.externalCustomerId = Optional.ofNullable(externalCustomerId);
            return this;
        }

        /**
         * <p>Filter by credit currency ID.</p>
         */
        @JsonSetter(value = "creditsCurrencyId", nulls = Nulls.SKIP)
        public Builder creditsCurrencyId(Optional<String> creditsCurrencyId) {
            this.creditsCurrencyId = creditsCurrencyId;
            return this;
        }

        public Builder creditsCurrencyId(String creditsCurrencyId) {
            this.creditsCurrencyId = Optional.ofNullable(creditsCurrencyId);
            return this;
        }

        /**
         * <p>Filter by the stable machine-readable key of the credit currency.</p>
         */
        @JsonSetter(value = "creditCurrencyKey", nulls = Nulls.SKIP)
        public Builder creditCurrencyKey(Optional<String> creditCurrencyKey) {
            this.creditCurrencyKey = creditCurrencyKey;
            return this;
        }

        public Builder creditCurrencyKey(String creditCurrencyKey) {
            this.creditCurrencyKey = Optional.ofNullable(creditCurrencyKey);
            return this;
        }

        /**
         * <p>Filter by transaction type.</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<ListCreditTransactionsRequestType> type) {
            this.type = type;
            return this;
        }

        public Builder type(ListCreditTransactionsRequestType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Filter by the order this transaction is linked to.</p>
         */
        @JsonSetter(value = "orderId", nulls = Nulls.SKIP)
        public Builder orderId(Optional<String> orderId) {
            this.orderId = orderId;
            return this;
        }

        public Builder orderId(String orderId) {
            this.orderId = Optional.ofNullable(orderId);
            return this;
        }

        /**
         * <p>Filter by the usage event that produced the transaction (exact match, untrimmed). Transactions with no event (grants, invoice-void clawbacks, manual adjustments) never match.</p>
         */
        @JsonSetter(value = "eventName", nulls = Nulls.SKIP)
        public Builder eventName(Optional<String> eventName) {
            this.eventName = eventName;
            return this;
        }

        public Builder eventName(String eventName) {
            this.eventName = Optional.ofNullable(eventName);
            return this;
        }

        /**
         * <p>Only transactions recorded on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.</p>
         */
        @JsonSetter(value = "createdAtFrom", nulls = Nulls.SKIP)
        public Builder createdAtFrom(Optional<String> createdAtFrom) {
            this.createdAtFrom = createdAtFrom;
            return this;
        }

        public Builder createdAtFrom(String createdAtFrom) {
            this.createdAtFrom = Optional.ofNullable(createdAtFrom);
            return this;
        }

        /**
         * <p>Only transactions recorded on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.</p>
         */
        @JsonSetter(value = "createdAtTo", nulls = Nulls.SKIP)
        public Builder createdAtTo(Optional<String> createdAtTo) {
            this.createdAtTo = createdAtTo;
            return this;
        }

        public Builder createdAtTo(String createdAtTo) {
            this.createdAtTo = Optional.ofNullable(createdAtTo);
            return this;
        }

        public ListCreditTransactionsRequest build() {
            return new ListCreditTransactionsRequest(
                    limit,
                    offset,
                    customerId,
                    externalCustomerId,
                    creditsCurrencyId,
                    creditCurrencyKey,
                    type,
                    orderId,
                    eventName,
                    createdAtFrom,
                    createdAtTo,
                    additionalProperties);
        }
    }
}
