/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.checkouts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.paid.api.core.ClientOptions;
import com.paid.api.core.MediaTypes;
import com.paid.api.core.ObjectMappers;
import com.paid.api.core.PaidApiApiException;
import com.paid.api.core.PaidApiException;
import com.paid.api.core.PaidApiHttpResponse;
import com.paid.api.core.QueryStringMapper;
import com.paid.api.core.RequestOptions;
import com.paid.api.errors.BadRequestError;
import com.paid.api.errors.ForbiddenError;
import com.paid.api.errors.InternalServerError;
import com.paid.api.errors.NotFoundError;
import com.paid.api.resources.checkouts.requests.ArchiveCheckoutRequest;
import com.paid.api.resources.checkouts.requests.CreateCheckoutRequest;
import com.paid.api.resources.checkouts.requests.GetCheckoutRequest;
import com.paid.api.resources.checkouts.requests.ListCheckoutsRequest;
import com.paid.api.types.Checkout;
import com.paid.api.types.CheckoutDetails;
import com.paid.api.types.CheckoutListResponse;
import com.paid.api.types.EmptyResponse;
import com.paid.api.types.ErrorResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawCheckoutsClient {
    protected final ClientOptions clientOptions;

    public RawCheckoutsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Get a list of checkouts for the organization
     */
    public PaidApiHttpResponse<CheckoutListResponse> listCheckouts() {
        return listCheckouts(ListCheckoutsRequest.builder().build());
    }

    /**
     * Get a list of checkouts for the organization
     */
    public PaidApiHttpResponse<CheckoutListResponse> listCheckouts(ListCheckoutsRequest request) {
        return listCheckouts(request, null);
    }

    /**
     * Get a list of checkouts for the organization
     */
    public PaidApiHttpResponse<CheckoutListResponse> listCheckouts(
            ListCheckoutsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("checkouts");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getOffset().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "offset", request.getOffset().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CheckoutListResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Creates a checkout link that generates a URL for a customer to complete a purchase
     */
    public PaidApiHttpResponse<Checkout> createCheckout(CreateCheckoutRequest request) {
        return createCheckout(request, null);
    }

    /**
     * Creates a checkout link that generates a URL for a customer to complete a purchase
     */
    public PaidApiHttpResponse<Checkout> createCheckout(CreateCheckoutRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("checkouts")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PaidApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Checkout.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a checkout by ID
     */
    public PaidApiHttpResponse<CheckoutDetails> getCheckout(String id) {
        return getCheckout(id, GetCheckoutRequest.builder().build());
    }

    /**
     * Get a checkout by ID
     */
    public PaidApiHttpResponse<CheckoutDetails> getCheckout(String id, GetCheckoutRequest request) {
        return getCheckout(id, request, null);
    }

    /**
     * Get a checkout by ID
     */
    public PaidApiHttpResponse<CheckoutDetails> getCheckout(
            String id, GetCheckoutRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("checkouts")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CheckoutDetails.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Archive a checkout by ID
     */
    public PaidApiHttpResponse<EmptyResponse> archiveCheckout(String id) {
        return archiveCheckout(id, ArchiveCheckoutRequest.builder().build());
    }

    /**
     * Archive a checkout by ID
     */
    public PaidApiHttpResponse<EmptyResponse> archiveCheckout(String id, ArchiveCheckoutRequest request) {
        return archiveCheckout(id, request, null);
    }

    /**
     * Archive a checkout by ID
     */
    public PaidApiHttpResponse<EmptyResponse> archiveCheckout(
            String id, ArchiveCheckoutRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("checkouts")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), EmptyResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }
}
