/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.valuereceipts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PublishValueReceiptBody.Builder.class)
public final class PublishValueReceiptBody {
    private final Optional<OffsetDateTime> publishExpiresAt;

    private final Map<String, Object> additionalProperties;

    private PublishValueReceiptBody(
            Optional<OffsetDateTime> publishExpiresAt, Map<String, Object> additionalProperties) {
        this.publishExpiresAt = publishExpiresAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getPublishExpiresAt() {
        if (publishExpiresAt == null) {
            return Optional.empty();
        }
        return publishExpiresAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("publishExpiresAt")
    private Optional<OffsetDateTime> _getPublishExpiresAt() {
        return publishExpiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PublishValueReceiptBody && equalTo((PublishValueReceiptBody) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PublishValueReceiptBody other) {
        return publishExpiresAt.equals(other.publishExpiresAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.publishExpiresAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<OffsetDateTime> publishExpiresAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PublishValueReceiptBody other) {
            publishExpiresAt(other.getPublishExpiresAt());
            return this;
        }

        @JsonSetter(value = "publishExpiresAt", nulls = Nulls.SKIP)
        public Builder publishExpiresAt(Optional<OffsetDateTime> publishExpiresAt) {
            this.publishExpiresAt = publishExpiresAt;
            return this;
        }

        public Builder publishExpiresAt(OffsetDateTime publishExpiresAt) {
            this.publishExpiresAt = Optional.ofNullable(publishExpiresAt);
            return this;
        }

        public Builder publishExpiresAt(Nullable<OffsetDateTime> publishExpiresAt) {
            if (publishExpiresAt.isNull()) {
                this.publishExpiresAt = null;
            } else if (publishExpiresAt.isEmpty()) {
                this.publishExpiresAt = Optional.empty();
            } else {
                this.publishExpiresAt = Optional.of(publishExpiresAt.get());
            }
            return this;
        }

        public PublishValueReceiptBody build() {
            return new PublishValueReceiptBody(publishExpiresAt, additionalProperties);
        }
    }
}
