/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.webhooks.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum UpdateWebhookRequestWebhookName {
    BILLING_INVOICE_CREATED("billing-invoice-created"),

    BILLING_INVOICE_PAID("billing-invoice-paid"),

    BILLING_CHECKOUT_CREATED("billing-checkout-created"),

    BILLING_CHECKOUT_COMPLETED("billing-checkout-completed"),

    BILLING_CHECKOUT_EXPIRED("billing-checkout-expired"),

    BILLING_PAYMENT_SUCCEEDED("billing-payment-succeeded"),

    BILLING_PAYMENT_FAILED("billing-payment-failed"),

    BILLING_CREDITS_DEPLETED("billing-credits-depleted"),

    BILLING_OVERAGE_INCURRED("billing-overage-incurred");

    private final String value;

    UpdateWebhookRequestWebhookName(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
