/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentAttribute.Builder.class)
public final class AgentAttribute {
    private final String name;

    private final boolean active;

    private final Pricing pricing;

    private final Map<String, Object> additionalProperties;

    private AgentAttribute(String name, boolean active, Pricing pricing, Map<String, Object> additionalProperties) {
        this.name = name;
        this.active = active;
        this.pricing = pricing;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    @JsonProperty("pricing")
    public Pricing getPricing() {
        return pricing;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentAttribute && equalTo((AgentAttribute) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentAttribute other) {
        return name.equals(other.name) && active == other.active && pricing.equals(other.pricing);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.active, this.pricing);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        ActiveStage name(@NotNull String name);

        Builder from(AgentAttribute other);
    }

    public interface ActiveStage {
        PricingStage active(boolean active);
    }

    public interface PricingStage {
        _FinalStage pricing(@NotNull Pricing pricing);
    }

    public interface _FinalStage {
        AgentAttribute build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, ActiveStage, PricingStage, _FinalStage {
        private String name;

        private boolean active;

        private Pricing pricing;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentAttribute other) {
            name(other.getName());
            active(other.getActive());
            pricing(other.getPricing());
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public ActiveStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("active")
        public PricingStage active(boolean active) {
            this.active = active;
            return this;
        }

        @java.lang.Override
        @JsonSetter("pricing")
        public _FinalStage pricing(@NotNull Pricing pricing) {
            this.pricing = Objects.requireNonNull(pricing, "pricing must not be null");
            return this;
        }

        @java.lang.Override
        public AgentAttribute build() {
            return new AgentAttribute(name, active, pricing, additionalProperties);
        }
    }
}
