/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BackfillResponse.Builder.class)
public final class BackfillResponse {
    private final String valueModelId;

    private final int version;

    private final Map<String, Object> additionalProperties;

    private BackfillResponse(String valueModelId, int version, Map<String, Object> additionalProperties) {
        this.valueModelId = valueModelId;
        this.version = version;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("valueModelId")
    public String getValueModelId() {
        return valueModelId;
    }

    @JsonProperty("version")
    public int getVersion() {
        return version;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BackfillResponse && equalTo((BackfillResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BackfillResponse other) {
        return valueModelId.equals(other.valueModelId) && version == other.version;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.valueModelId, this.version);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ValueModelIdStage builder() {
        return new Builder();
    }

    public interface ValueModelIdStage {
        VersionStage valueModelId(@NotNull String valueModelId);

        Builder from(BackfillResponse other);
    }

    public interface VersionStage {
        _FinalStage version(int version);
    }

    public interface _FinalStage {
        BackfillResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ValueModelIdStage, VersionStage, _FinalStage {
        private String valueModelId;

        private int version;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BackfillResponse other) {
            valueModelId(other.getValueModelId());
            version(other.getVersion());
            return this;
        }

        @java.lang.Override
        @JsonSetter("valueModelId")
        public VersionStage valueModelId(@NotNull String valueModelId) {
            this.valueModelId = Objects.requireNonNull(valueModelId, "valueModelId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("version")
        public _FinalStage version(int version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        public BackfillResponse build() {
            return new BackfillResponse(valueModelId, version, additionalProperties);
        }
    }
}
