/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem.Builder.class)
public final class CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem {
    private final Optional<Integer> upTo;

    private final int creditUnits;

    private final Map<String, Object> additionalProperties;

    private CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem(
            Optional<Integer> upTo, int creditUnits, Map<String, Object> additionalProperties) {
        this.upTo = upTo;
        this.creditUnits = creditUnits;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<Integer> getUpTo() {
        if (upTo == null) {
            return Optional.empty();
        }
        return upTo;
    }

    @JsonProperty("creditUnits")
    public int getCreditUnits() {
        return creditUnits;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("upTo")
    private Optional<Integer> _getUpTo() {
        return upTo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem
                && equalTo((CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem other) {
        return upTo.equals(other.upTo) && creditUnits == other.creditUnits;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.upTo, this.creditUnits);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreditUnitsStage builder() {
        return new Builder();
    }

    public interface CreditUnitsStage {
        _FinalStage creditUnits(int creditUnits);

        Builder from(CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem other);
    }

    public interface _FinalStage {
        CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem build();

        _FinalStage upTo(Optional<Integer> upTo);

        _FinalStage upTo(Integer upTo);

        _FinalStage upTo(Nullable<Integer> upTo);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CreditUnitsStage, _FinalStage {
        private int creditUnits;

        private Optional<Integer> upTo = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem other) {
            upTo(other.getUpTo());
            creditUnits(other.getCreditUnits());
            return this;
        }

        @java.lang.Override
        @JsonSetter("creditUnits")
        public _FinalStage creditUnits(int creditUnits) {
            this.creditUnits = creditUnits;
            return this;
        }

        @java.lang.Override
        public _FinalStage upTo(Nullable<Integer> upTo) {
            if (upTo.isNull()) {
                this.upTo = null;
            } else if (upTo.isEmpty()) {
                this.upTo = Optional.empty();
            } else {
                this.upTo = Optional.of(upTo.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage upTo(Integer upTo) {
            this.upTo = Optional.ofNullable(upTo);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "upTo", nulls = Nulls.SKIP)
        public _FinalStage upTo(Optional<Integer> upTo) {
            this.upTo = upTo;
            return this;
        }

        @java.lang.Override
        public CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem build() {
            return new CreateOrderLineAttributeRequestPricingCreditUnitBracketsItem(
                    upTo, creditUnits, additionalProperties);
        }
    }
}
