/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreditGrantAddAxisOptions.Builder.class)
public final class CreditGrantAddAxisOptions {
    private final AmendmentAxisRelevance relevance;

    private final List<AmendmentPricingClause> appliesTo;

    private final List<CreditGrantAddAxisOptionsOptionsItem> options;

    private final Map<String, Object> additionalProperties;

    private CreditGrantAddAxisOptions(
            AmendmentAxisRelevance relevance,
            List<AmendmentPricingClause> appliesTo,
            List<CreditGrantAddAxisOptionsOptionsItem> options,
            Map<String, Object> additionalProperties) {
        this.relevance = relevance;
        this.appliesTo = appliesTo;
        this.options = options;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("relevance")
    public AmendmentAxisRelevance getRelevance() {
        return relevance;
    }

    /**
     * @return Pricing this axis applies to. Match every non-empty list. Empty lists constrain nothing. Evaluate against the attribute you are adding.
     */
    @JsonProperty("appliesTo")
    public List<AmendmentPricingClause> getAppliesTo() {
        return appliesTo;
    }

    @JsonProperty("options")
    public List<CreditGrantAddAxisOptionsOptionsItem> getOptions() {
        return options;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreditGrantAddAxisOptions && equalTo((CreditGrantAddAxisOptions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreditGrantAddAxisOptions other) {
        return relevance.equals(other.relevance) && appliesTo.equals(other.appliesTo) && options.equals(other.options);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.relevance, this.appliesTo, this.options);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RelevanceStage builder() {
        return new Builder();
    }

    public interface RelevanceStage {
        _FinalStage relevance(@NotNull AmendmentAxisRelevance relevance);

        Builder from(CreditGrantAddAxisOptions other);
    }

    public interface _FinalStage {
        CreditGrantAddAxisOptions build();

        /**
         * <p>Pricing this axis applies to. Match every non-empty list. Empty lists constrain nothing. Evaluate against the attribute you are adding.</p>
         */
        _FinalStage appliesTo(List<AmendmentPricingClause> appliesTo);

        _FinalStage addAppliesTo(AmendmentPricingClause appliesTo);

        _FinalStage addAllAppliesTo(List<AmendmentPricingClause> appliesTo);

        _FinalStage options(List<CreditGrantAddAxisOptionsOptionsItem> options);

        _FinalStage addOptions(CreditGrantAddAxisOptionsOptionsItem options);

        _FinalStage addAllOptions(List<CreditGrantAddAxisOptionsOptionsItem> options);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RelevanceStage, _FinalStage {
        private AmendmentAxisRelevance relevance;

        private List<CreditGrantAddAxisOptionsOptionsItem> options = new ArrayList<>();

        private List<AmendmentPricingClause> appliesTo = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreditGrantAddAxisOptions other) {
            relevance(other.getRelevance());
            appliesTo(other.getAppliesTo());
            options(other.getOptions());
            return this;
        }

        @java.lang.Override
        @JsonSetter("relevance")
        public _FinalStage relevance(@NotNull AmendmentAxisRelevance relevance) {
            this.relevance = Objects.requireNonNull(relevance, "relevance must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllOptions(List<CreditGrantAddAxisOptionsOptionsItem> options) {
            this.options.addAll(options);
            return this;
        }

        @java.lang.Override
        public _FinalStage addOptions(CreditGrantAddAxisOptionsOptionsItem options) {
            this.options.add(options);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public _FinalStage options(List<CreditGrantAddAxisOptionsOptionsItem> options) {
            this.options.clear();
            this.options.addAll(options);
            return this;
        }

        /**
         * <p>Pricing this axis applies to. Match every non-empty list. Empty lists constrain nothing. Evaluate against the attribute you are adding.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllAppliesTo(List<AmendmentPricingClause> appliesTo) {
            this.appliesTo.addAll(appliesTo);
            return this;
        }

        /**
         * <p>Pricing this axis applies to. Match every non-empty list. Empty lists constrain nothing. Evaluate against the attribute you are adding.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAppliesTo(AmendmentPricingClause appliesTo) {
            this.appliesTo.add(appliesTo);
            return this;
        }

        /**
         * <p>Pricing this axis applies to. Match every non-empty list. Empty lists constrain nothing. Evaluate against the attribute you are adding.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "appliesTo", nulls = Nulls.SKIP)
        public _FinalStage appliesTo(List<AmendmentPricingClause> appliesTo) {
            this.appliesTo.clear();
            this.appliesTo.addAll(appliesTo);
            return this;
        }

        @java.lang.Override
        public CreditGrantAddAxisOptions build() {
            return new CreditGrantAddAxisOptions(relevance, appliesTo, options, additionalProperties);
        }
    }
}
