/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerUnitCapSetResponse.Builder.class)
public final class CustomerUnitCapSetResponse {
    private final String externalCustomerUnitId;

    private final String customerId;

    private final String creditsCurrencyId;

    private final CustomerUnitCapOpenPolicy policy;

    private final Optional<CustomerUnitCapCurrentPeriod> currentPeriod;

    private final Map<String, Object> additionalProperties;

    private CustomerUnitCapSetResponse(
            String externalCustomerUnitId,
            String customerId,
            String creditsCurrencyId,
            CustomerUnitCapOpenPolicy policy,
            Optional<CustomerUnitCapCurrentPeriod> currentPeriod,
            Map<String, Object> additionalProperties) {
        this.externalCustomerUnitId = externalCustomerUnitId;
        this.customerId = customerId;
        this.creditsCurrencyId = creditsCurrencyId;
        this.policy = policy;
        this.currentPeriod = currentPeriod;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Your own id for the unit (its <code>externalId</code>), the identifier the unit and cap routes take.
     */
    @JsonProperty("externalCustomerUnitId")
    public String getExternalCustomerUnitId() {
        return externalCustomerUnitId;
    }

    /**
     * @return The Paid display id of the customer the unit belongs to.
     */
    @JsonProperty("customerId")
    public String getCustomerId() {
        return customerId;
    }

    /**
     * @return The credits currency the cap was set on: the requested <code>creditsCurrencyId</code>, or the organization's only credits currency when it was omitted.
     */
    @JsonProperty("creditsCurrencyId")
    public String getCreditsCurrencyId() {
        return creditsCurrencyId;
    }

    @JsonProperty("policy")
    public CustomerUnitCapOpenPolicy getPolicy() {
        return policy;
    }

    @JsonIgnore
    public Optional<CustomerUnitCapCurrentPeriod> getCurrentPeriod() {
        if (currentPeriod == null) {
            return Optional.empty();
        }
        return currentPeriod;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("currentPeriod")
    private Optional<CustomerUnitCapCurrentPeriod> _getCurrentPeriod() {
        return currentPeriod;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerUnitCapSetResponse && equalTo((CustomerUnitCapSetResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerUnitCapSetResponse other) {
        return externalCustomerUnitId.equals(other.externalCustomerUnitId)
                && customerId.equals(other.customerId)
                && creditsCurrencyId.equals(other.creditsCurrencyId)
                && policy.equals(other.policy)
                && currentPeriod.equals(other.currentPeriod);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.externalCustomerUnitId, this.customerId, this.creditsCurrencyId, this.policy, this.currentPeriod);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ExternalCustomerUnitIdStage builder() {
        return new Builder();
    }

    public interface ExternalCustomerUnitIdStage {
        /**
         * <p>Your own id for the unit (its <code>externalId</code>), the identifier the unit and cap routes take.</p>
         */
        CustomerIdStage externalCustomerUnitId(@NotNull String externalCustomerUnitId);

        Builder from(CustomerUnitCapSetResponse other);
    }

    public interface CustomerIdStage {
        /**
         * <p>The Paid display id of the customer the unit belongs to.</p>
         */
        CreditsCurrencyIdStage customerId(@NotNull String customerId);
    }

    public interface CreditsCurrencyIdStage {
        /**
         * <p>The credits currency the cap was set on: the requested <code>creditsCurrencyId</code>, or the organization's only credits currency when it was omitted.</p>
         */
        PolicyStage creditsCurrencyId(@NotNull String creditsCurrencyId);
    }

    public interface PolicyStage {
        _FinalStage policy(@NotNull CustomerUnitCapOpenPolicy policy);
    }

    public interface _FinalStage {
        CustomerUnitCapSetResponse build();

        _FinalStage currentPeriod(Optional<CustomerUnitCapCurrentPeriod> currentPeriod);

        _FinalStage currentPeriod(CustomerUnitCapCurrentPeriod currentPeriod);

        _FinalStage currentPeriod(Nullable<CustomerUnitCapCurrentPeriod> currentPeriod);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ExternalCustomerUnitIdStage, CustomerIdStage, CreditsCurrencyIdStage, PolicyStage, _FinalStage {
        private String externalCustomerUnitId;

        private String customerId;

        private String creditsCurrencyId;

        private CustomerUnitCapOpenPolicy policy;

        private Optional<CustomerUnitCapCurrentPeriod> currentPeriod = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomerUnitCapSetResponse other) {
            externalCustomerUnitId(other.getExternalCustomerUnitId());
            customerId(other.getCustomerId());
            creditsCurrencyId(other.getCreditsCurrencyId());
            policy(other.getPolicy());
            currentPeriod(other.getCurrentPeriod());
            return this;
        }

        /**
         * <p>Your own id for the unit (its <code>externalId</code>), the identifier the unit and cap routes take.</p>
         * <p>Your own id for the unit (its <code>externalId</code>), the identifier the unit and cap routes take.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("externalCustomerUnitId")
        public CustomerIdStage externalCustomerUnitId(@NotNull String externalCustomerUnitId) {
            this.externalCustomerUnitId =
                    Objects.requireNonNull(externalCustomerUnitId, "externalCustomerUnitId must not be null");
            return this;
        }

        /**
         * <p>The Paid display id of the customer the unit belongs to.</p>
         * <p>The Paid display id of the customer the unit belongs to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("customerId")
        public CreditsCurrencyIdStage customerId(@NotNull String customerId) {
            this.customerId = Objects.requireNonNull(customerId, "customerId must not be null");
            return this;
        }

        /**
         * <p>The credits currency the cap was set on: the requested <code>creditsCurrencyId</code>, or the organization's only credits currency when it was omitted.</p>
         * <p>The credits currency the cap was set on: the requested <code>creditsCurrencyId</code>, or the organization's only credits currency when it was omitted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("creditsCurrencyId")
        public PolicyStage creditsCurrencyId(@NotNull String creditsCurrencyId) {
            this.creditsCurrencyId = Objects.requireNonNull(creditsCurrencyId, "creditsCurrencyId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("policy")
        public _FinalStage policy(@NotNull CustomerUnitCapOpenPolicy policy) {
            this.policy = Objects.requireNonNull(policy, "policy must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage currentPeriod(Nullable<CustomerUnitCapCurrentPeriod> currentPeriod) {
            if (currentPeriod.isNull()) {
                this.currentPeriod = null;
            } else if (currentPeriod.isEmpty()) {
                this.currentPeriod = Optional.empty();
            } else {
                this.currentPeriod = Optional.of(currentPeriod.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage currentPeriod(CustomerUnitCapCurrentPeriod currentPeriod) {
            this.currentPeriod = Optional.ofNullable(currentPeriod);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "currentPeriod", nulls = Nulls.SKIP)
        public _FinalStage currentPeriod(Optional<CustomerUnitCapCurrentPeriod> currentPeriod) {
            this.currentPeriod = currentPeriod;
            return this;
        }

        @java.lang.Override
        public CustomerUnitCapSetResponse build() {
            return new CustomerUnitCapSetResponse(
                    externalCustomerUnitId, customerId, creditsCurrencyId, policy, currentPeriod, additionalProperties);
        }
    }
}
