/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Customer.Builder.class)
public final class Customer {
    private final String id;

    private final String organizationId;

    private final String name;

    private final Optional<String> externalId;

    private final Optional<String> phone;

    private final Optional<Double> employeeCount;

    private final Optional<Double> annualRevenue;

    private final Optional<TaxExemptStatus> taxExemptStatus;

    private final Optional<CreationSource> creationSource;

    private final Optional<CreationState> creationState;

    private final Optional<String> website;

    private final Optional<Address> billingAddress;

    private final Map<String, Object> additionalProperties;

    private Customer(
            String id,
            String organizationId,
            String name,
            Optional<String> externalId,
            Optional<String> phone,
            Optional<Double> employeeCount,
            Optional<Double> annualRevenue,
            Optional<TaxExemptStatus> taxExemptStatus,
            Optional<CreationSource> creationSource,
            Optional<CreationState> creationState,
            Optional<String> website,
            Optional<Address> billingAddress,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.organizationId = organizationId;
        this.name = name;
        this.externalId = externalId;
        this.phone = phone;
        this.employeeCount = employeeCount;
        this.annualRevenue = annualRevenue;
        this.taxExemptStatus = taxExemptStatus;
        this.creationSource = creationSource;
        this.creationState = creationState;
        this.website = website;
        this.billingAddress = billingAddress;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("organizationId")
    public String getOrganizationId() {
        return organizationId;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("externalId")
    public Optional<String> getExternalId() {
        return externalId;
    }

    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    @JsonProperty("employeeCount")
    public Optional<Double> getEmployeeCount() {
        return employeeCount;
    }

    @JsonProperty("annualRevenue")
    public Optional<Double> getAnnualRevenue() {
        return annualRevenue;
    }

    @JsonProperty("taxExemptStatus")
    public Optional<TaxExemptStatus> getTaxExemptStatus() {
        return taxExemptStatus;
    }

    @JsonProperty("creationSource")
    public Optional<CreationSource> getCreationSource() {
        return creationSource;
    }

    @JsonProperty("creationState")
    public Optional<CreationState> getCreationState() {
        return creationState;
    }

    @JsonProperty("website")
    public Optional<String> getWebsite() {
        return website;
    }

    @JsonProperty("billingAddress")
    public Optional<Address> getBillingAddress() {
        return billingAddress;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Customer && equalTo((Customer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Customer other) {
        return id.equals(other.id)
                && organizationId.equals(other.organizationId)
                && name.equals(other.name)
                && externalId.equals(other.externalId)
                && phone.equals(other.phone)
                && employeeCount.equals(other.employeeCount)
                && annualRevenue.equals(other.annualRevenue)
                && taxExemptStatus.equals(other.taxExemptStatus)
                && creationSource.equals(other.creationSource)
                && creationState.equals(other.creationState)
                && website.equals(other.website)
                && billingAddress.equals(other.billingAddress);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.organizationId,
                this.name,
                this.externalId,
                this.phone,
                this.employeeCount,
                this.annualRevenue,
                this.taxExemptStatus,
                this.creationSource,
                this.creationState,
                this.website,
                this.billingAddress);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        OrganizationIdStage id(@NotNull String id);

        Builder from(Customer other);
    }

    public interface OrganizationIdStage {
        NameStage organizationId(@NotNull String organizationId);
    }

    public interface NameStage {
        _FinalStage name(@NotNull String name);
    }

    public interface _FinalStage {
        Customer build();

        _FinalStage externalId(Optional<String> externalId);

        _FinalStage externalId(String externalId);

        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);

        _FinalStage employeeCount(Optional<Double> employeeCount);

        _FinalStage employeeCount(Double employeeCount);

        _FinalStage annualRevenue(Optional<Double> annualRevenue);

        _FinalStage annualRevenue(Double annualRevenue);

        _FinalStage taxExemptStatus(Optional<TaxExemptStatus> taxExemptStatus);

        _FinalStage taxExemptStatus(TaxExemptStatus taxExemptStatus);

        _FinalStage creationSource(Optional<CreationSource> creationSource);

        _FinalStage creationSource(CreationSource creationSource);

        _FinalStage creationState(Optional<CreationState> creationState);

        _FinalStage creationState(CreationState creationState);

        _FinalStage website(Optional<String> website);

        _FinalStage website(String website);

        _FinalStage billingAddress(Optional<Address> billingAddress);

        _FinalStage billingAddress(Address billingAddress);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, OrganizationIdStage, NameStage, _FinalStage {
        private String id;

        private String organizationId;

        private String name;

        private Optional<Address> billingAddress = Optional.empty();

        private Optional<String> website = Optional.empty();

        private Optional<CreationState> creationState = Optional.empty();

        private Optional<CreationSource> creationSource = Optional.empty();

        private Optional<TaxExemptStatus> taxExemptStatus = Optional.empty();

        private Optional<Double> annualRevenue = Optional.empty();

        private Optional<Double> employeeCount = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Customer other) {
            id(other.getId());
            organizationId(other.getOrganizationId());
            name(other.getName());
            externalId(other.getExternalId());
            phone(other.getPhone());
            employeeCount(other.getEmployeeCount());
            annualRevenue(other.getAnnualRevenue());
            taxExemptStatus(other.getTaxExemptStatus());
            creationSource(other.getCreationSource());
            creationState(other.getCreationState());
            website(other.getWebsite());
            billingAddress(other.getBillingAddress());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrganizationIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("organizationId")
        public NameStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage billingAddress(Address billingAddress) {
            this.billingAddress = Optional.ofNullable(billingAddress);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingAddress", nulls = Nulls.SKIP)
        public _FinalStage billingAddress(Optional<Address> billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        @java.lang.Override
        public _FinalStage website(String website) {
            this.website = Optional.ofNullable(website);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "website", nulls = Nulls.SKIP)
        public _FinalStage website(Optional<String> website) {
            this.website = website;
            return this;
        }

        @java.lang.Override
        public _FinalStage creationState(CreationState creationState) {
            this.creationState = Optional.ofNullable(creationState);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "creationState", nulls = Nulls.SKIP)
        public _FinalStage creationState(Optional<CreationState> creationState) {
            this.creationState = creationState;
            return this;
        }

        @java.lang.Override
        public _FinalStage creationSource(CreationSource creationSource) {
            this.creationSource = Optional.ofNullable(creationSource);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "creationSource", nulls = Nulls.SKIP)
        public _FinalStage creationSource(Optional<CreationSource> creationSource) {
            this.creationSource = creationSource;
            return this;
        }

        @java.lang.Override
        public _FinalStage taxExemptStatus(TaxExemptStatus taxExemptStatus) {
            this.taxExemptStatus = Optional.ofNullable(taxExemptStatus);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "taxExemptStatus", nulls = Nulls.SKIP)
        public _FinalStage taxExemptStatus(Optional<TaxExemptStatus> taxExemptStatus) {
            this.taxExemptStatus = taxExemptStatus;
            return this;
        }

        @java.lang.Override
        public _FinalStage annualRevenue(Double annualRevenue) {
            this.annualRevenue = Optional.ofNullable(annualRevenue);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "annualRevenue", nulls = Nulls.SKIP)
        public _FinalStage annualRevenue(Optional<Double> annualRevenue) {
            this.annualRevenue = annualRevenue;
            return this;
        }

        @java.lang.Override
        public _FinalStage employeeCount(Double employeeCount) {
            this.employeeCount = Optional.ofNullable(employeeCount);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "employeeCount", nulls = Nulls.SKIP)
        public _FinalStage employeeCount(Optional<Double> employeeCount) {
            this.employeeCount = employeeCount;
            return this;
        }

        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        @java.lang.Override
        public _FinalStage externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "externalId", nulls = Nulls.SKIP)
        public _FinalStage externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        @java.lang.Override
        public Customer build() {
            return new Customer(
                    id,
                    organizationId,
                    name,
                    externalId,
                    phone,
                    employeeCount,
                    annualRevenue,
                    taxExemptStatus,
                    creationSource,
                    creationState,
                    website,
                    billingAddress,
                    additionalProperties);
        }
    }
}
