/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerUnitCapCurrentPeriod.Builder.class)
public final class CustomerUnitCapCurrentPeriod {
    private final CustomerUnitCapPeriod window;

    private final double used;

    private final double remaining;

    private final Map<String, Object> additionalProperties;

    private CustomerUnitCapCurrentPeriod(
            CustomerUnitCapPeriod window, double used, double remaining, Map<String, Object> additionalProperties) {
        this.window = window;
        this.used = used;
        this.remaining = remaining;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("window")
    public CustomerUnitCapPeriod getWindow() {
        return window;
    }

    /**
     * @return Credits of this currency spent by this unit and its descendants during the window. JSON number; exact within ±2^53.
     */
    @JsonProperty("used")
    public double getUsed() {
        return used;
    }

    /**
     * @return <code>amount - used</code>; negative once the cap is exceeded. Advisory: spend may land between this read and the next burn.
     */
    @JsonProperty("remaining")
    public double getRemaining() {
        return remaining;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerUnitCapCurrentPeriod && equalTo((CustomerUnitCapCurrentPeriod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerUnitCapCurrentPeriod other) {
        return window.equals(other.window) && used == other.used && remaining == other.remaining;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.window, this.used, this.remaining);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static WindowStage builder() {
        return new Builder();
    }

    public interface WindowStage {
        UsedStage window(@NotNull CustomerUnitCapPeriod window);

        Builder from(CustomerUnitCapCurrentPeriod other);
    }

    public interface UsedStage {
        /**
         * <p>Credits of this currency spent by this unit and its descendants during the window. JSON number; exact within ±2^53.</p>
         */
        RemainingStage used(double used);
    }

    public interface RemainingStage {
        /**
         * <p><code>amount - used</code>; negative once the cap is exceeded. Advisory: spend may land between this read and the next burn.</p>
         */
        _FinalStage remaining(double remaining);
    }

    public interface _FinalStage {
        CustomerUnitCapCurrentPeriod build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements WindowStage, UsedStage, RemainingStage, _FinalStage {
        private CustomerUnitCapPeriod window;

        private double used;

        private double remaining;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomerUnitCapCurrentPeriod other) {
            window(other.getWindow());
            used(other.getUsed());
            remaining(other.getRemaining());
            return this;
        }

        @java.lang.Override
        @JsonSetter("window")
        public UsedStage window(@NotNull CustomerUnitCapPeriod window) {
            this.window = Objects.requireNonNull(window, "window must not be null");
            return this;
        }

        /**
         * <p>Credits of this currency spent by this unit and its descendants during the window. JSON number; exact within ±2^53.</p>
         * <p>Credits of this currency spent by this unit and its descendants during the window. JSON number; exact within ±2^53.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("used")
        public RemainingStage used(double used) {
            this.used = used;
            return this;
        }

        /**
         * <p><code>amount - used</code>; negative once the cap is exceeded. Advisory: spend may land between this read and the next burn.</p>
         * <p><code>amount - used</code>; negative once the cap is exceeded. Advisory: spend may land between this read and the next burn.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("remaining")
        public _FinalStage remaining(double remaining) {
            this.remaining = remaining;
            return this;
        }

        @java.lang.Override
        public CustomerUnitCapCurrentPeriod build() {
            return new CustomerUnitCapCurrentPeriod(window, used, remaining, additionalProperties);
        }
    }
}
