/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomViewValidationFinding.Builder.class)
public final class CustomViewValidationFinding {
    private final String reason;

    private final String error;

    private final Optional<String> details;

    private final Map<String, Object> additionalProperties;

    private CustomViewValidationFinding(
            String reason, String error, Optional<String> details, Map<String, Object> additionalProperties) {
        this.reason = reason;
        this.error = error;
        this.details = details;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Stable machine-readable code for this finding.
     */
    @JsonProperty("reason")
    public String getReason() {
        return reason;
    }

    /**
     * @return Human-readable description of what to fix.
     */
    @JsonProperty("error")
    public String getError() {
        return error;
    }

    /**
     * @return Extra context for this finding, when available.
     */
    @JsonProperty("details")
    public Optional<String> getDetails() {
        return details;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomViewValidationFinding && equalTo((CustomViewValidationFinding) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomViewValidationFinding other) {
        return reason.equals(other.reason) && error.equals(other.error) && details.equals(other.details);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.reason, this.error, this.details);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReasonStage builder() {
        return new Builder();
    }

    public interface ReasonStage {
        /**
         * <p>Stable machine-readable code for this finding.</p>
         */
        ErrorStage reason(@NotNull String reason);

        Builder from(CustomViewValidationFinding other);
    }

    public interface ErrorStage {
        /**
         * <p>Human-readable description of what to fix.</p>
         */
        _FinalStage error(@NotNull String error);
    }

    public interface _FinalStage {
        CustomViewValidationFinding build();

        /**
         * <p>Extra context for this finding, when available.</p>
         */
        _FinalStage details(Optional<String> details);

        _FinalStage details(String details);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReasonStage, ErrorStage, _FinalStage {
        private String reason;

        private String error;

        private Optional<String> details = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomViewValidationFinding other) {
            reason(other.getReason());
            error(other.getError());
            details(other.getDetails());
            return this;
        }

        /**
         * <p>Stable machine-readable code for this finding.</p>
         * <p>Stable machine-readable code for this finding.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reason")
        public ErrorStage reason(@NotNull String reason) {
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
            return this;
        }

        /**
         * <p>Human-readable description of what to fix.</p>
         * <p>Human-readable description of what to fix.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("error")
        public _FinalStage error(@NotNull String error) {
            this.error = Objects.requireNonNull(error, "error must not be null");
            return this;
        }

        /**
         * <p>Extra context for this finding, when available.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage details(String details) {
            this.details = Optional.ofNullable(details);
            return this;
        }

        /**
         * <p>Extra context for this finding, when available.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "details", nulls = Nulls.SKIP)
        public _FinalStage details(Optional<String> details) {
            this.details = details;
            return this;
        }

        @java.lang.Override
        public CustomViewValidationFinding build() {
            return new CustomViewValidationFinding(reason, error, details, additionalProperties);
        }
    }
}
