/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerStateSeats.Builder.class)
public final class CustomerStateSeats {
    private final int total;

    private final int assigned;

    private final int unassigned;

    private final List<CustomerStateSeat> data;

    private final Map<String, Object> additionalProperties;

    private CustomerStateSeats(
            int total,
            int assigned,
            int unassigned,
            List<CustomerStateSeat> data,
            Map<String, Object> additionalProperties) {
        this.total = total;
        this.assigned = assigned;
        this.unassigned = unassigned;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("total")
    public int getTotal() {
        return total;
    }

    @JsonProperty("assigned")
    public int getAssigned() {
        return assigned;
    }

    @JsonProperty("unassigned")
    public int getUnassigned() {
        return unassigned;
    }

    @JsonProperty("data")
    public List<CustomerStateSeat> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerStateSeats && equalTo((CustomerStateSeats) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerStateSeats other) {
        return total == other.total
                && assigned == other.assigned
                && unassigned == other.unassigned
                && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.total, this.assigned, this.unassigned, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TotalStage builder() {
        return new Builder();
    }

    public interface TotalStage {
        AssignedStage total(int total);

        Builder from(CustomerStateSeats other);
    }

    public interface AssignedStage {
        UnassignedStage assigned(int assigned);
    }

    public interface UnassignedStage {
        _FinalStage unassigned(int unassigned);
    }

    public interface _FinalStage {
        CustomerStateSeats build();

        _FinalStage data(List<CustomerStateSeat> data);

        _FinalStage addData(CustomerStateSeat data);

        _FinalStage addAllData(List<CustomerStateSeat> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TotalStage, AssignedStage, UnassignedStage, _FinalStage {
        private int total;

        private int assigned;

        private int unassigned;

        private List<CustomerStateSeat> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomerStateSeats other) {
            total(other.getTotal());
            assigned(other.getAssigned());
            unassigned(other.getUnassigned());
            data(other.getData());
            return this;
        }

        @java.lang.Override
        @JsonSetter("total")
        public AssignedStage total(int total) {
            this.total = total;
            return this;
        }

        @java.lang.Override
        @JsonSetter("assigned")
        public UnassignedStage assigned(int assigned) {
            this.assigned = assigned;
            return this;
        }

        @java.lang.Override
        @JsonSetter("unassigned")
        public _FinalStage unassigned(int unassigned) {
            this.unassigned = unassigned;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<CustomerStateSeat> data) {
            this.data.addAll(data);
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(CustomerStateSeat data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<CustomerStateSeat> data) {
            this.data.clear();
            this.data.addAll(data);
            return this;
        }

        @java.lang.Override
        public CustomerStateSeats build() {
            return new CustomerStateSeats(total, assigned, unassigned, data, additionalProperties);
        }
    }
}
