/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerStateOrder.Builder.class)
public final class CustomerStateOrder {
    private final String id;

    private final Optional<String> externalId;

    private final String name;

    private final CustomerStateOrderState state;

    private final String currency;

    private final OffsetDateTime startDate;

    private final Optional<OffsetDateTime> endDate;

    private final Optional<OffsetDateTime> effectiveUntil;

    private final Map<String, Object> additionalProperties;

    private CustomerStateOrder(
            String id,
            Optional<String> externalId,
            String name,
            CustomerStateOrderState state,
            String currency,
            OffsetDateTime startDate,
            Optional<OffsetDateTime> endDate,
            Optional<OffsetDateTime> effectiveUntil,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.externalId = externalId;
        this.name = name;
        this.state = state;
        this.currency = currency;
        this.startDate = startDate;
        this.endDate = endDate;
        this.effectiveUntil = effectiveUntil;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonIgnore
    public Optional<String> getExternalId() {
        if (externalId == null) {
            return Optional.empty();
        }
        return externalId;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("state")
    public CustomerStateOrderState getState() {
        return state;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @JsonProperty("startDate")
    public OffsetDateTime getStartDate() {
        return startDate;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getEndDate() {
        if (endDate == null) {
            return Optional.empty();
        }
        return endDate;
    }

    /**
     * @return When the order stops applying; null means no scheduled end.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getEffectiveUntil() {
        if (effectiveUntil == null) {
            return Optional.empty();
        }
        return effectiveUntil;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("externalId")
    private Optional<String> _getExternalId() {
        return externalId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("endDate")
    private Optional<OffsetDateTime> _getEndDate() {
        return endDate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("effectiveUntil")
    private Optional<OffsetDateTime> _getEffectiveUntil() {
        return effectiveUntil;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerStateOrder && equalTo((CustomerStateOrder) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerStateOrder other) {
        return id.equals(other.id)
                && externalId.equals(other.externalId)
                && name.equals(other.name)
                && state.equals(other.state)
                && currency.equals(other.currency)
                && startDate.equals(other.startDate)
                && endDate.equals(other.endDate)
                && effectiveUntil.equals(other.effectiveUntil);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.externalId,
                this.name,
                this.state,
                this.currency,
                this.startDate,
                this.endDate,
                this.effectiveUntil);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        NameStage id(@NotNull String id);

        Builder from(CustomerStateOrder other);
    }

    public interface NameStage {
        StateStage name(@NotNull String name);
    }

    public interface StateStage {
        CurrencyStage state(@NotNull CustomerStateOrderState state);
    }

    public interface CurrencyStage {
        StartDateStage currency(@NotNull String currency);
    }

    public interface StartDateStage {
        _FinalStage startDate(@NotNull OffsetDateTime startDate);
    }

    public interface _FinalStage {
        CustomerStateOrder build();

        _FinalStage externalId(Optional<String> externalId);

        _FinalStage externalId(String externalId);

        _FinalStage externalId(Nullable<String> externalId);

        _FinalStage endDate(Optional<OffsetDateTime> endDate);

        _FinalStage endDate(OffsetDateTime endDate);

        _FinalStage endDate(Nullable<OffsetDateTime> endDate);

        /**
         * <p>When the order stops applying; null means no scheduled end.</p>
         */
        _FinalStage effectiveUntil(Optional<OffsetDateTime> effectiveUntil);

        _FinalStage effectiveUntil(OffsetDateTime effectiveUntil);

        _FinalStage effectiveUntil(Nullable<OffsetDateTime> effectiveUntil);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, NameStage, StateStage, CurrencyStage, StartDateStage, _FinalStage {
        private String id;

        private String name;

        private CustomerStateOrderState state;

        private String currency;

        private OffsetDateTime startDate;

        private Optional<OffsetDateTime> effectiveUntil = Optional.empty();

        private Optional<OffsetDateTime> endDate = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomerStateOrder other) {
            id(other.getId());
            externalId(other.getExternalId());
            name(other.getName());
            state(other.getState());
            currency(other.getCurrency());
            startDate(other.getStartDate());
            endDate(other.getEndDate());
            effectiveUntil(other.getEffectiveUntil());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public StateStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("state")
        public CurrencyStage state(@NotNull CustomerStateOrderState state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public StartDateStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("startDate")
        public _FinalStage startDate(@NotNull OffsetDateTime startDate) {
            this.startDate = Objects.requireNonNull(startDate, "startDate must not be null");
            return this;
        }

        /**
         * <p>When the order stops applying; null means no scheduled end.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage effectiveUntil(Nullable<OffsetDateTime> effectiveUntil) {
            if (effectiveUntil.isNull()) {
                this.effectiveUntil = null;
            } else if (effectiveUntil.isEmpty()) {
                this.effectiveUntil = Optional.empty();
            } else {
                this.effectiveUntil = Optional.of(effectiveUntil.get());
            }
            return this;
        }

        /**
         * <p>When the order stops applying; null means no scheduled end.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage effectiveUntil(OffsetDateTime effectiveUntil) {
            this.effectiveUntil = Optional.ofNullable(effectiveUntil);
            return this;
        }

        /**
         * <p>When the order stops applying; null means no scheduled end.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "effectiveUntil", nulls = Nulls.SKIP)
        public _FinalStage effectiveUntil(Optional<OffsetDateTime> effectiveUntil) {
            this.effectiveUntil = effectiveUntil;
            return this;
        }

        @java.lang.Override
        public _FinalStage endDate(Nullable<OffsetDateTime> endDate) {
            if (endDate.isNull()) {
                this.endDate = null;
            } else if (endDate.isEmpty()) {
                this.endDate = Optional.empty();
            } else {
                this.endDate = Optional.of(endDate.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage endDate(OffsetDateTime endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "endDate", nulls = Nulls.SKIP)
        public _FinalStage endDate(Optional<OffsetDateTime> endDate) {
            this.endDate = endDate;
            return this;
        }

        @java.lang.Override
        public _FinalStage externalId(Nullable<String> externalId) {
            if (externalId.isNull()) {
                this.externalId = null;
            } else if (externalId.isEmpty()) {
                this.externalId = Optional.empty();
            } else {
                this.externalId = Optional.of(externalId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "externalId", nulls = Nulls.SKIP)
        public _FinalStage externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        @java.lang.Override
        public CustomerStateOrder build() {
            return new CustomerStateOrder(
                    id, externalId, name, state, currency, startDate, endDate, effectiveUntil, additionalProperties);
        }
    }
}
