/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerUnitCapScheduleAnchorDay.Builder.class)
public final class CustomerUnitCapScheduleAnchorDay {
    private final CustomerUnitCapScheduleAnchorDayType type;

    private final int anchorDay;

    private final Map<String, Object> additionalProperties;

    private CustomerUnitCapScheduleAnchorDay(
            CustomerUnitCapScheduleAnchorDayType type, int anchorDay, Map<String, Object> additionalProperties) {
        this.type = type;
        this.anchorDay = anchorDay;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public CustomerUnitCapScheduleAnchorDayType getType() {
        return type;
    }

    /**
     * @return UTC day of month, clamped to the last day in shorter months.
     */
    @JsonProperty("anchorDay")
    public int getAnchorDay() {
        return anchorDay;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerUnitCapScheduleAnchorDay && equalTo((CustomerUnitCapScheduleAnchorDay) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerUnitCapScheduleAnchorDay other) {
        return type.equals(other.type) && anchorDay == other.anchorDay;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.anchorDay);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        AnchorDayStage type(@NotNull CustomerUnitCapScheduleAnchorDayType type);

        Builder from(CustomerUnitCapScheduleAnchorDay other);
    }

    public interface AnchorDayStage {
        /**
         * <p>UTC day of month, clamped to the last day in shorter months.</p>
         */
        _FinalStage anchorDay(int anchorDay);
    }

    public interface _FinalStage {
        CustomerUnitCapScheduleAnchorDay build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, AnchorDayStage, _FinalStage {
        private CustomerUnitCapScheduleAnchorDayType type;

        private int anchorDay;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomerUnitCapScheduleAnchorDay other) {
            type(other.getType());
            anchorDay(other.getAnchorDay());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public AnchorDayStage type(@NotNull CustomerUnitCapScheduleAnchorDayType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>UTC day of month, clamped to the last day in shorter months.</p>
         * <p>UTC day of month, clamped to the last day in shorter months.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("anchorDay")
        public _FinalStage anchorDay(int anchorDay) {
            this.anchorDay = anchorDay;
            return this;
        }

        @java.lang.Override
        public CustomerUnitCapScheduleAnchorDay build() {
            return new CustomerUnitCapScheduleAnchorDay(type, anchorDay, additionalProperties);
        }
    }
}
