/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomerFundingInstructionsCreateRequest.Builder.class)
public final class CustomerFundingInstructionsCreateRequest {
    private final Optional<String> currency;

    private final Map<String, Object> additionalProperties;

    private CustomerFundingInstructionsCreateRequest(
            Optional<String> currency, Map<String, Object> additionalProperties) {
        this.currency = currency;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Currency of the virtual bank account. Only USD is supported today; defaults to USD.
     */
    @JsonProperty("currency")
    public Optional<String> getCurrency() {
        return currency;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomerFundingInstructionsCreateRequest
                && equalTo((CustomerFundingInstructionsCreateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomerFundingInstructionsCreateRequest other) {
        return currency.equals(other.currency);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.currency);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> currency = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CustomerFundingInstructionsCreateRequest other) {
            currency(other.getCurrency());
            return this;
        }

        /**
         * <p>Currency of the virtual bank account. Only USD is supported today; defaults to USD.</p>
         */
        @JsonSetter(value = "currency", nulls = Nulls.SKIP)
        public Builder currency(Optional<String> currency) {
            this.currency = currency;
            return this;
        }

        public Builder currency(String currency) {
            this.currency = Optional.ofNullable(currency);
            return this;
        }

        public CustomerFundingInstructionsCreateRequest build() {
            return new CustomerFundingInstructionsCreateRequest(currency, additionalProperties);
        }
    }
}
