/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrderSeat.Builder.class)
public final class OrderSeat {
    private final String id;

    private final String orderId;

    private final Optional<String> productExternalId;

    private final SeatAssignmentStatus status;

    private final Optional<SeatAssignee> assignee;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private OrderSeat(
            String id,
            String orderId,
            Optional<String> productExternalId,
            SeatAssignmentStatus status,
            Optional<SeatAssignee> assignee,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.orderId = orderId;
        this.productExternalId = productExternalId;
        this.status = status;
        this.assignee = assignee;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("orderId")
    public String getOrderId() {
        return orderId;
    }

    @JsonIgnore
    public Optional<String> getProductExternalId() {
        if (productExternalId == null) {
            return Optional.empty();
        }
        return productExternalId;
    }

    @JsonProperty("status")
    public SeatAssignmentStatus getStatus() {
        return status;
    }

    @JsonIgnore
    public Optional<SeatAssignee> getAssignee() {
        if (assignee == null) {
            return Optional.empty();
        }
        return assignee;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("productExternalId")
    private Optional<String> _getProductExternalId() {
        return productExternalId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("assignee")
    private Optional<SeatAssignee> _getAssignee() {
        return assignee;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrderSeat && equalTo((OrderSeat) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrderSeat other) {
        return id.equals(other.id)
                && orderId.equals(other.orderId)
                && productExternalId.equals(other.productExternalId)
                && status.equals(other.status)
                && assignee.equals(other.assignee)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.orderId,
                this.productExternalId,
                this.status,
                this.assignee,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        OrderIdStage id(@NotNull String id);

        Builder from(OrderSeat other);
    }

    public interface OrderIdStage {
        StatusStage orderId(@NotNull String orderId);
    }

    public interface StatusStage {
        CreatedAtStage status(@NotNull SeatAssignmentStatus status);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        OrderSeat build();

        _FinalStage productExternalId(Optional<String> productExternalId);

        _FinalStage productExternalId(String productExternalId);

        _FinalStage productExternalId(Nullable<String> productExternalId);

        _FinalStage assignee(Optional<SeatAssignee> assignee);

        _FinalStage assignee(SeatAssignee assignee);

        _FinalStage assignee(Nullable<SeatAssignee> assignee);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, OrderIdStage, StatusStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String orderId;

        private SeatAssignmentStatus status;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<SeatAssignee> assignee = Optional.empty();

        private Optional<String> productExternalId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrderSeat other) {
            id(other.getId());
            orderId(other.getOrderId());
            productExternalId(other.getProductExternalId());
            status(other.getStatus());
            assignee(other.getAssignee());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrderIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("orderId")
        public StatusStage orderId(@NotNull String orderId) {
            this.orderId = Objects.requireNonNull(orderId, "orderId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public CreatedAtStage status(@NotNull SeatAssignmentStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage assignee(Nullable<SeatAssignee> assignee) {
            if (assignee.isNull()) {
                this.assignee = null;
            } else if (assignee.isEmpty()) {
                this.assignee = Optional.empty();
            } else {
                this.assignee = Optional.of(assignee.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage assignee(SeatAssignee assignee) {
            this.assignee = Optional.ofNullable(assignee);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "assignee", nulls = Nulls.SKIP)
        public _FinalStage assignee(Optional<SeatAssignee> assignee) {
            this.assignee = assignee;
            return this;
        }

        @java.lang.Override
        public _FinalStage productExternalId(Nullable<String> productExternalId) {
            if (productExternalId.isNull()) {
                this.productExternalId = null;
            } else if (productExternalId.isEmpty()) {
                this.productExternalId = Optional.empty();
            } else {
                this.productExternalId = Optional.of(productExternalId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage productExternalId(String productExternalId) {
            this.productExternalId = Optional.ofNullable(productExternalId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "productExternalId", nulls = Nulls.SKIP)
        public _FinalStage productExternalId(Optional<String> productExternalId) {
            this.productExternalId = productExternalId;
            return this;
        }

        @java.lang.Override
        public OrderSeat build() {
            return new OrderSeat(
                    id, orderId, productExternalId, status, assignee, createdAt, updatedAt, additionalProperties);
        }
    }
}
