/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentAllocation.Builder.class)
public final class PaymentAllocation {
    private final String id;

    private final String paymentId;

    private final String invoiceId;

    private final String invoiceLineId;

    private final int amount;

    private final String currency;

    private final String type;

    private final String status;

    private final OffsetDateTime allocationDate;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private PaymentAllocation(
            String id,
            String paymentId,
            String invoiceId,
            String invoiceLineId,
            int amount,
            String currency,
            String type,
            String status,
            OffsetDateTime allocationDate,
            OffsetDateTime createdAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.paymentId = paymentId;
        this.invoiceId = invoiceId;
        this.invoiceLineId = invoiceLineId;
        this.amount = amount;
        this.currency = currency;
        this.type = type;
        this.status = status;
        this.allocationDate = allocationDate;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique payment allocation identifier.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The payment the amount was allocated from.
     */
    @JsonProperty("paymentId")
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * @return The invoice the allocated line belongs to.
     */
    @JsonProperty("invoiceId")
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * @return The invoice line the amount was allocated to, as returned by the invoice lines endpoint.
     */
    @JsonProperty("invoiceLineId")
    public String getInvoiceLineId() {
        return invoiceLineId;
    }

    /**
     * @return Allocated amount in cents (minor currency units).
     */
    @JsonProperty("amount")
    public int getAmount() {
        return amount;
    }

    /**
     * @return Three-letter ISO currency code.
     */
    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * @return Allocation type: allocated or unallocated.
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return Allocation status: posted, applied, or cancelled.
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    /**
     * @return When the allocation was made.
     */
    @JsonProperty("allocationDate")
    public OffsetDateTime getAllocationDate() {
        return allocationDate;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentAllocation && equalTo((PaymentAllocation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentAllocation other) {
        return id.equals(other.id)
                && paymentId.equals(other.paymentId)
                && invoiceId.equals(other.invoiceId)
                && invoiceLineId.equals(other.invoiceLineId)
                && amount == other.amount
                && currency.equals(other.currency)
                && type.equals(other.type)
                && status.equals(other.status)
                && allocationDate.equals(other.allocationDate)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.paymentId,
                this.invoiceId,
                this.invoiceLineId,
                this.amount,
                this.currency,
                this.type,
                this.status,
                this.allocationDate,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique payment allocation identifier.</p>
         */
        PaymentIdStage id(@NotNull String id);

        Builder from(PaymentAllocation other);
    }

    public interface PaymentIdStage {
        /**
         * <p>The payment the amount was allocated from.</p>
         */
        InvoiceIdStage paymentId(@NotNull String paymentId);
    }

    public interface InvoiceIdStage {
        /**
         * <p>The invoice the allocated line belongs to.</p>
         */
        InvoiceLineIdStage invoiceId(@NotNull String invoiceId);
    }

    public interface InvoiceLineIdStage {
        /**
         * <p>The invoice line the amount was allocated to, as returned by the invoice lines endpoint.</p>
         */
        AmountStage invoiceLineId(@NotNull String invoiceLineId);
    }

    public interface AmountStage {
        /**
         * <p>Allocated amount in cents (minor currency units).</p>
         */
        CurrencyStage amount(int amount);
    }

    public interface CurrencyStage {
        /**
         * <p>Three-letter ISO currency code.</p>
         */
        TypeStage currency(@NotNull String currency);
    }

    public interface TypeStage {
        /**
         * <p>Allocation type: allocated or unallocated.</p>
         */
        StatusStage type(@NotNull String type);
    }

    public interface StatusStage {
        /**
         * <p>Allocation status: posted, applied, or cancelled.</p>
         */
        AllocationDateStage status(@NotNull String status);
    }

    public interface AllocationDateStage {
        /**
         * <p>When the allocation was made.</p>
         */
        CreatedAtStage allocationDate(@NotNull OffsetDateTime allocationDate);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        PaymentAllocation build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    PaymentIdStage,
                    InvoiceIdStage,
                    InvoiceLineIdStage,
                    AmountStage,
                    CurrencyStage,
                    TypeStage,
                    StatusStage,
                    AllocationDateStage,
                    CreatedAtStage,
                    _FinalStage {
        private String id;

        private String paymentId;

        private String invoiceId;

        private String invoiceLineId;

        private int amount;

        private String currency;

        private String type;

        private String status;

        private OffsetDateTime allocationDate;

        private OffsetDateTime createdAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentAllocation other) {
            id(other.getId());
            paymentId(other.getPaymentId());
            invoiceId(other.getInvoiceId());
            invoiceLineId(other.getInvoiceLineId());
            amount(other.getAmount());
            currency(other.getCurrency());
            type(other.getType());
            status(other.getStatus());
            allocationDate(other.getAllocationDate());
            createdAt(other.getCreatedAt());
            return this;
        }

        /**
         * <p>Unique payment allocation identifier.</p>
         * <p>Unique payment allocation identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public PaymentIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The payment the amount was allocated from.</p>
         * <p>The payment the amount was allocated from.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("paymentId")
        public InvoiceIdStage paymentId(@NotNull String paymentId) {
            this.paymentId = Objects.requireNonNull(paymentId, "paymentId must not be null");
            return this;
        }

        /**
         * <p>The invoice the allocated line belongs to.</p>
         * <p>The invoice the allocated line belongs to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("invoiceId")
        public InvoiceLineIdStage invoiceId(@NotNull String invoiceId) {
            this.invoiceId = Objects.requireNonNull(invoiceId, "invoiceId must not be null");
            return this;
        }

        /**
         * <p>The invoice line the amount was allocated to, as returned by the invoice lines endpoint.</p>
         * <p>The invoice line the amount was allocated to, as returned by the invoice lines endpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("invoiceLineId")
        public AmountStage invoiceLineId(@NotNull String invoiceLineId) {
            this.invoiceLineId = Objects.requireNonNull(invoiceLineId, "invoiceLineId must not be null");
            return this;
        }

        /**
         * <p>Allocated amount in cents (minor currency units).</p>
         * <p>Allocated amount in cents (minor currency units).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("amount")
        public CurrencyStage amount(int amount) {
            this.amount = amount;
            return this;
        }

        /**
         * <p>Three-letter ISO currency code.</p>
         * <p>Three-letter ISO currency code.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("currency")
        public TypeStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        /**
         * <p>Allocation type: allocated or unallocated.</p>
         * <p>Allocation type: allocated or unallocated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public StatusStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Allocation status: posted, applied, or cancelled.</p>
         * <p>Allocation status: posted, applied, or cancelled.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public AllocationDateStage status(@NotNull String status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>When the allocation was made.</p>
         * <p>When the allocation was made.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("allocationDate")
        public CreatedAtStage allocationDate(@NotNull OffsetDateTime allocationDate) {
            this.allocationDate = Objects.requireNonNull(allocationDate, "allocationDate must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public PaymentAllocation build() {
            return new PaymentAllocation(
                    id,
                    paymentId,
                    invoiceId,
                    invoiceLineId,
                    amount,
                    currency,
                    type,
                    status,
                    allocationDate,
                    createdAt,
                    additionalProperties);
        }
    }
}
