/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PricePoint.Builder.class)
public final class PricePoint {
    private final Optional<String> currency;

    private final Optional<Double> unitPrice;

    private final Optional<Double> minQuantity;

    private final Optional<List<Tier>> tiers;

    private final Map<String, Object> additionalProperties;

    private PricePoint(
            Optional<String> currency,
            Optional<Double> unitPrice,
            Optional<Double> minQuantity,
            Optional<List<Tier>> tiers,
            Map<String, Object> additionalProperties) {
        this.currency = currency;
        this.unitPrice = unitPrice;
        this.minQuantity = minQuantity;
        this.tiers = tiers;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("currency")
    public Optional<String> getCurrency() {
        return currency;
    }

    @JsonProperty("unitPrice")
    public Optional<Double> getUnitPrice() {
        return unitPrice;
    }

    @JsonProperty("minQuantity")
    public Optional<Double> getMinQuantity() {
        return minQuantity;
    }

    @JsonProperty("tiers")
    public Optional<List<Tier>> getTiers() {
        return tiers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PricePoint && equalTo((PricePoint) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PricePoint other) {
        return currency.equals(other.currency)
                && unitPrice.equals(other.unitPrice)
                && minQuantity.equals(other.minQuantity)
                && tiers.equals(other.tiers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.currency, this.unitPrice, this.minQuantity, this.tiers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> currency = Optional.empty();

        private Optional<Double> unitPrice = Optional.empty();

        private Optional<Double> minQuantity = Optional.empty();

        private Optional<List<Tier>> tiers = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PricePoint other) {
            currency(other.getCurrency());
            unitPrice(other.getUnitPrice());
            minQuantity(other.getMinQuantity());
            tiers(other.getTiers());
            return this;
        }

        @JsonSetter(value = "currency", nulls = Nulls.SKIP)
        public Builder currency(Optional<String> currency) {
            this.currency = currency;
            return this;
        }

        public Builder currency(String currency) {
            this.currency = Optional.ofNullable(currency);
            return this;
        }

        @JsonSetter(value = "unitPrice", nulls = Nulls.SKIP)
        public Builder unitPrice(Optional<Double> unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        public Builder unitPrice(Double unitPrice) {
            this.unitPrice = Optional.ofNullable(unitPrice);
            return this;
        }

        @JsonSetter(value = "minQuantity", nulls = Nulls.SKIP)
        public Builder minQuantity(Optional<Double> minQuantity) {
            this.minQuantity = minQuantity;
            return this;
        }

        public Builder minQuantity(Double minQuantity) {
            this.minQuantity = Optional.ofNullable(minQuantity);
            return this;
        }

        @JsonSetter(value = "tiers", nulls = Nulls.SKIP)
        public Builder tiers(Optional<List<Tier>> tiers) {
            this.tiers = tiers;
            return this;
        }

        public Builder tiers(List<Tier> tiers) {
            this.tiers = Optional.ofNullable(tiers);
            return this;
        }

        public PricePoint build() {
            return new PricePoint(currency, unitPrice, minQuantity, tiers, additionalProperties);
        }
    }
}
