/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PricingOutputPricingType {
    RECURRING_PER_UNIT("RecurringPerUnit"),

    RECURRING_GRADUATED("RecurringGraduated"),

    RECURRING_VOLUME("RecurringVolume"),

    RECURRING_PERCENT_OF_TOTAL("RecurringPercentOfTotal"),

    USAGE_PER_UNIT("UsagePerUnit"),

    USAGE_GRADUATED("UsageGraduated"),

    USAGE_VOLUME("UsageVolume"),

    USAGE_PREPAID_CREDITS("UsagePrepaidCredits"),

    USAGE_BRACKETED_PREPAID_CREDITS("UsageBracketedPrepaidCredits"),

    USAGE_COST_PLUS("UsageCostPlus"),

    ONE_TIME_PER_UNIT("OneTimePerUnit"),

    SEAT_BASED_PER_UNIT("SeatBasedPerUnit"),

    SEAT_BASED_GRADUATED("SeatBasedGraduated"),

    SEAT_BASED_VOLUME("SeatBasedVolume"),

    SEAT_BASED_PREPAID_CREDITS("SeatBasedPrepaidCredits");

    private final String value;

    PricingOutputPricingType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
