/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.paid.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = ProductAttribution.Deserializer.class)
public final class ProductAttribution {
    private final Object value;

    private final int type;

    private ProductAttribution(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ProductById) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ProductByExternalId) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProductAttribution && equalTo((ProductAttribution) other);
    }

    private boolean equalTo(ProductAttribution other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ProductAttribution of(ProductById value) {
        return new ProductAttribution(value, 0);
    }

    public static ProductAttribution of(ProductByExternalId value) {
        return new ProductAttribution(value, 1);
    }

    public interface Visitor<T> {
        T visit(ProductById value);

        T visit(ProductByExternalId value);
    }

    static final class Deserializer extends StdDeserializer<ProductAttribution> {
        Deserializer() {
            super(ProductAttribution.class);
        }

        @java.lang.Override
        public ProductAttribution deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ProductById.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ProductByExternalId.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
