/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProductSeatBasedVolumeInput.Builder.class)
public final class ProductSeatBasedVolumeInput {
    private final ProductSeatBasedVolumeInputBillingFrequency billingFrequency;

    private final Optional<Integer> billingFrequencyCustomMonths;

    private final Optional<ProductSeatBasedVolumeInputBillingType> billingType;

    private final List<ProductTieredPricePoint> pricePoints;

    private final Map<String, Object> additionalProperties;

    private ProductSeatBasedVolumeInput(
            ProductSeatBasedVolumeInputBillingFrequency billingFrequency,
            Optional<Integer> billingFrequencyCustomMonths,
            Optional<ProductSeatBasedVolumeInputBillingType> billingType,
            List<ProductTieredPricePoint> pricePoints,
            Map<String, Object> additionalProperties) {
        this.billingFrequency = billingFrequency;
        this.billingFrequencyCustomMonths = billingFrequencyCustomMonths;
        this.billingType = billingType;
        this.pricePoints = pricePoints;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("billingFrequency")
    public ProductSeatBasedVolumeInputBillingFrequency getBillingFrequency() {
        return billingFrequency;
    }

    @JsonProperty("billingFrequencyCustomMonths")
    public Optional<Integer> getBillingFrequencyCustomMonths() {
        return billingFrequencyCustomMonths;
    }

    @JsonProperty("billingType")
    public Optional<ProductSeatBasedVolumeInputBillingType> getBillingType() {
        return billingType;
    }

    @JsonProperty("pricePoints")
    public List<ProductTieredPricePoint> getPricePoints() {
        return pricePoints;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProductSeatBasedVolumeInput && equalTo((ProductSeatBasedVolumeInput) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProductSeatBasedVolumeInput other) {
        return billingFrequency.equals(other.billingFrequency)
                && billingFrequencyCustomMonths.equals(other.billingFrequencyCustomMonths)
                && billingType.equals(other.billingType)
                && pricePoints.equals(other.pricePoints);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.billingFrequency, this.billingFrequencyCustomMonths, this.billingType, this.pricePoints);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static BillingFrequencyStage builder() {
        return new Builder();
    }

    public interface BillingFrequencyStage {
        _FinalStage billingFrequency(@NotNull ProductSeatBasedVolumeInputBillingFrequency billingFrequency);

        Builder from(ProductSeatBasedVolumeInput other);
    }

    public interface _FinalStage {
        ProductSeatBasedVolumeInput build();

        _FinalStage billingFrequencyCustomMonths(Optional<Integer> billingFrequencyCustomMonths);

        _FinalStage billingFrequencyCustomMonths(Integer billingFrequencyCustomMonths);

        _FinalStage billingType(Optional<ProductSeatBasedVolumeInputBillingType> billingType);

        _FinalStage billingType(ProductSeatBasedVolumeInputBillingType billingType);

        _FinalStage pricePoints(List<ProductTieredPricePoint> pricePoints);

        _FinalStage addPricePoints(ProductTieredPricePoint pricePoints);

        _FinalStage addAllPricePoints(List<ProductTieredPricePoint> pricePoints);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements BillingFrequencyStage, _FinalStage {
        private ProductSeatBasedVolumeInputBillingFrequency billingFrequency;

        private List<ProductTieredPricePoint> pricePoints = new ArrayList<>();

        private Optional<ProductSeatBasedVolumeInputBillingType> billingType = Optional.empty();

        private Optional<Integer> billingFrequencyCustomMonths = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProductSeatBasedVolumeInput other) {
            billingFrequency(other.getBillingFrequency());
            billingFrequencyCustomMonths(other.getBillingFrequencyCustomMonths());
            billingType(other.getBillingType());
            pricePoints(other.getPricePoints());
            return this;
        }

        @java.lang.Override
        @JsonSetter("billingFrequency")
        public _FinalStage billingFrequency(@NotNull ProductSeatBasedVolumeInputBillingFrequency billingFrequency) {
            this.billingFrequency = Objects.requireNonNull(billingFrequency, "billingFrequency must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllPricePoints(List<ProductTieredPricePoint> pricePoints) {
            this.pricePoints.addAll(pricePoints);
            return this;
        }

        @java.lang.Override
        public _FinalStage addPricePoints(ProductTieredPricePoint pricePoints) {
            this.pricePoints.add(pricePoints);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pricePoints", nulls = Nulls.SKIP)
        public _FinalStage pricePoints(List<ProductTieredPricePoint> pricePoints) {
            this.pricePoints.clear();
            this.pricePoints.addAll(pricePoints);
            return this;
        }

        @java.lang.Override
        public _FinalStage billingType(ProductSeatBasedVolumeInputBillingType billingType) {
            this.billingType = Optional.ofNullable(billingType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingType", nulls = Nulls.SKIP)
        public _FinalStage billingType(Optional<ProductSeatBasedVolumeInputBillingType> billingType) {
            this.billingType = billingType;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingFrequencyCustomMonths(Integer billingFrequencyCustomMonths) {
            this.billingFrequencyCustomMonths = Optional.ofNullable(billingFrequencyCustomMonths);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingFrequencyCustomMonths", nulls = Nulls.SKIP)
        public _FinalStage billingFrequencyCustomMonths(Optional<Integer> billingFrequencyCustomMonths) {
            this.billingFrequencyCustomMonths = billingFrequencyCustomMonths;
            return this;
        }

        @java.lang.Override
        public ProductSeatBasedVolumeInput build() {
            return new ProductSeatBasedVolumeInput(
                    billingFrequency, billingFrequencyCustomMonths, billingType, pricePoints, additionalProperties);
        }
    }
}
