/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ProductRecurringPercentOfTotalInputBillingType {
    ADVANCE("Advance"),

    ARREARS("Arrears");

    private final String value;

    ProductRecurringPercentOfTotalInputBillingType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
