/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SignalSummaryBandsDimensionBracketsItem.Builder.class)
public final class SignalSummaryBandsDimensionBracketsItem {
    private final Optional<Integer> from;

    private final Optional<Integer> upTo;

    private final Optional<String> slug;

    private final Optional<String> group;

    private final Map<String, Object> additionalProperties;

    private SignalSummaryBandsDimensionBracketsItem(
            Optional<Integer> from,
            Optional<Integer> upTo,
            Optional<String> slug,
            Optional<String> group,
            Map<String, Object> additionalProperties) {
        this.from = from;
        this.upTo = upTo;
        this.slug = slug;
        this.group = group;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Inclusive lower bound. Only meaningful on the first bracket, where it sets the floor of the banded range. Defaults to 1.
     */
    @JsonProperty("from")
    public Optional<Integer> getFrom() {
        return from;
    }

    /**
     * @return Inclusive upper bound for this band. Null on the final bracket for an open-ended top band.
     */
    @JsonIgnore
    public Optional<Integer> getUpTo() {
        if (upTo == null) {
            return Optional.empty();
        }
        return upTo;
    }

    @JsonProperty("slug")
    public Optional<String> getSlug() {
        return slug;
    }

    @JsonProperty("group")
    public Optional<String> getGroup() {
        return group;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("upTo")
    private Optional<Integer> _getUpTo() {
        return upTo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SignalSummaryBandsDimensionBracketsItem
                && equalTo((SignalSummaryBandsDimensionBracketsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SignalSummaryBandsDimensionBracketsItem other) {
        return from.equals(other.from)
                && upTo.equals(other.upTo)
                && slug.equals(other.slug)
                && group.equals(other.group);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.from, this.upTo, this.slug, this.group);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> from = Optional.empty();

        private Optional<Integer> upTo = Optional.empty();

        private Optional<String> slug = Optional.empty();

        private Optional<String> group = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SignalSummaryBandsDimensionBracketsItem other) {
            from(other.getFrom());
            upTo(other.getUpTo());
            slug(other.getSlug());
            group(other.getGroup());
            return this;
        }

        /**
         * <p>Inclusive lower bound. Only meaningful on the first bracket, where it sets the floor of the banded range. Defaults to 1.</p>
         */
        @JsonSetter(value = "from", nulls = Nulls.SKIP)
        public Builder from(Optional<Integer> from) {
            this.from = from;
            return this;
        }

        public Builder from(Integer from) {
            this.from = Optional.ofNullable(from);
            return this;
        }

        /**
         * <p>Inclusive upper bound for this band. Null on the final bracket for an open-ended top band.</p>
         */
        @JsonSetter(value = "upTo", nulls = Nulls.SKIP)
        public Builder upTo(Optional<Integer> upTo) {
            this.upTo = upTo;
            return this;
        }

        public Builder upTo(Integer upTo) {
            this.upTo = Optional.ofNullable(upTo);
            return this;
        }

        public Builder upTo(Nullable<Integer> upTo) {
            if (upTo.isNull()) {
                this.upTo = null;
            } else if (upTo.isEmpty()) {
                this.upTo = Optional.empty();
            } else {
                this.upTo = Optional.of(upTo.get());
            }
            return this;
        }

        @JsonSetter(value = "slug", nulls = Nulls.SKIP)
        public Builder slug(Optional<String> slug) {
            this.slug = slug;
            return this;
        }

        public Builder slug(String slug) {
            this.slug = Optional.ofNullable(slug);
            return this;
        }

        @JsonSetter(value = "group", nulls = Nulls.SKIP)
        public Builder group(Optional<String> group) {
            this.group = group;
            return this;
        }

        public Builder group(String group) {
            this.group = Optional.ofNullable(group);
            return this;
        }

        public SignalSummaryBandsDimensionBracketsItem build() {
            return new SignalSummaryBandsDimensionBracketsItem(from, upTo, slug, group, additionalProperties);
        }
    }
}
