/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TracesResponse.Builder.class)
public final class TracesResponse {
    private final List<Trace> traces;

    private final PaginationMeta meta;

    private final Map<String, Object> additionalProperties;

    private TracesResponse(List<Trace> traces, PaginationMeta meta, Map<String, Object> additionalProperties) {
        this.traces = traces;
        this.meta = meta;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("traces")
    public List<Trace> getTraces() {
        return traces;
    }

    @JsonProperty("meta")
    public PaginationMeta getMeta() {
        return meta;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TracesResponse && equalTo((TracesResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TracesResponse other) {
        return traces.equals(other.traces) && meta.equals(other.meta);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.traces, this.meta);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MetaStage builder() {
        return new Builder();
    }

    public interface MetaStage {
        _FinalStage meta(@NotNull PaginationMeta meta);

        Builder from(TracesResponse other);
    }

    public interface _FinalStage {
        TracesResponse build();

        _FinalStage traces(List<Trace> traces);

        _FinalStage addTraces(Trace traces);

        _FinalStage addAllTraces(List<Trace> traces);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MetaStage, _FinalStage {
        private PaginationMeta meta;

        private List<Trace> traces = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TracesResponse other) {
            traces(other.getTraces());
            meta(other.getMeta());
            return this;
        }

        @java.lang.Override
        @JsonSetter("meta")
        public _FinalStage meta(@NotNull PaginationMeta meta) {
            this.meta = Objects.requireNonNull(meta, "meta must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllTraces(List<Trace> traces) {
            if (traces != null) {
                this.traces.addAll(traces);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addTraces(Trace traces) {
            this.traces.add(traces);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "traces", nulls = Nulls.SKIP)
        public _FinalStage traces(List<Trace> traces) {
            this.traces.clear();
            if (traces != null) {
                this.traces.addAll(traces);
            }
            return this;
        }

        @java.lang.Override
        public TracesResponse build() {
            return new TracesResponse(traces, meta, additionalProperties);
        }
    }
}
