/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UsagePrepaidCreditsInput.Builder.class)
public final class UsagePrepaidCreditsInput {
    private final String eventName;

    private final String creditsCurrencyId;

    private final double creditCost;

    private final Optional<Double> unitValue;

    private final Optional<UsagePrepaidCreditsInputBillingFrequency> billingFrequency;

    private final Optional<Integer> billingFrequencyCustomMonths;

    private final Optional<UsagePrepaidCreditsInputBillingType> billingType;

    private final Optional<List<SimplePricePoint>> pricePoints;

    private final Map<String, Object> additionalProperties;

    private UsagePrepaidCreditsInput(
            String eventName,
            String creditsCurrencyId,
            double creditCost,
            Optional<Double> unitValue,
            Optional<UsagePrepaidCreditsInputBillingFrequency> billingFrequency,
            Optional<Integer> billingFrequencyCustomMonths,
            Optional<UsagePrepaidCreditsInputBillingType> billingType,
            Optional<List<SimplePricePoint>> pricePoints,
            Map<String, Object> additionalProperties) {
        this.eventName = eventName;
        this.creditsCurrencyId = creditsCurrencyId;
        this.creditCost = creditCost;
        this.unitValue = unitValue;
        this.billingFrequency = billingFrequency;
        this.billingFrequencyCustomMonths = billingFrequencyCustomMonths;
        this.billingType = billingType;
        this.pricePoints = pricePoints;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("eventName")
    public String getEventName() {
        return eventName;
    }

    @JsonProperty("creditsCurrencyId")
    public String getCreditsCurrencyId() {
        return creditsCurrencyId;
    }

    @JsonProperty("creditCost")
    public double getCreditCost() {
        return creditCost;
    }

    @JsonProperty("unitValue")
    public Optional<Double> getUnitValue() {
        return unitValue;
    }

    @JsonProperty("billingFrequency")
    public Optional<UsagePrepaidCreditsInputBillingFrequency> getBillingFrequency() {
        return billingFrequency;
    }

    @JsonProperty("billingFrequencyCustomMonths")
    public Optional<Integer> getBillingFrequencyCustomMonths() {
        return billingFrequencyCustomMonths;
    }

    @JsonProperty("billingType")
    public Optional<UsagePrepaidCreditsInputBillingType> getBillingType() {
        return billingType;
    }

    @JsonProperty("pricePoints")
    public Optional<List<SimplePricePoint>> getPricePoints() {
        return pricePoints;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UsagePrepaidCreditsInput && equalTo((UsagePrepaidCreditsInput) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UsagePrepaidCreditsInput other) {
        return eventName.equals(other.eventName)
                && creditsCurrencyId.equals(other.creditsCurrencyId)
                && creditCost == other.creditCost
                && unitValue.equals(other.unitValue)
                && billingFrequency.equals(other.billingFrequency)
                && billingFrequencyCustomMonths.equals(other.billingFrequencyCustomMonths)
                && billingType.equals(other.billingType)
                && pricePoints.equals(other.pricePoints);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.eventName,
                this.creditsCurrencyId,
                this.creditCost,
                this.unitValue,
                this.billingFrequency,
                this.billingFrequencyCustomMonths,
                this.billingType,
                this.pricePoints);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EventNameStage builder() {
        return new Builder();
    }

    public interface EventNameStage {
        CreditsCurrencyIdStage eventName(@NotNull String eventName);

        Builder from(UsagePrepaidCreditsInput other);
    }

    public interface CreditsCurrencyIdStage {
        CreditCostStage creditsCurrencyId(@NotNull String creditsCurrencyId);
    }

    public interface CreditCostStage {
        _FinalStage creditCost(double creditCost);
    }

    public interface _FinalStage {
        UsagePrepaidCreditsInput build();

        _FinalStage unitValue(Optional<Double> unitValue);

        _FinalStage unitValue(Double unitValue);

        _FinalStage billingFrequency(Optional<UsagePrepaidCreditsInputBillingFrequency> billingFrequency);

        _FinalStage billingFrequency(UsagePrepaidCreditsInputBillingFrequency billingFrequency);

        _FinalStage billingFrequencyCustomMonths(Optional<Integer> billingFrequencyCustomMonths);

        _FinalStage billingFrequencyCustomMonths(Integer billingFrequencyCustomMonths);

        _FinalStage billingType(Optional<UsagePrepaidCreditsInputBillingType> billingType);

        _FinalStage billingType(UsagePrepaidCreditsInputBillingType billingType);

        _FinalStage pricePoints(Optional<List<SimplePricePoint>> pricePoints);

        _FinalStage pricePoints(List<SimplePricePoint> pricePoints);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EventNameStage, CreditsCurrencyIdStage, CreditCostStage, _FinalStage {
        private String eventName;

        private String creditsCurrencyId;

        private double creditCost;

        private Optional<List<SimplePricePoint>> pricePoints = Optional.empty();

        private Optional<UsagePrepaidCreditsInputBillingType> billingType = Optional.empty();

        private Optional<Integer> billingFrequencyCustomMonths = Optional.empty();

        private Optional<UsagePrepaidCreditsInputBillingFrequency> billingFrequency = Optional.empty();

        private Optional<Double> unitValue = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UsagePrepaidCreditsInput other) {
            eventName(other.getEventName());
            creditsCurrencyId(other.getCreditsCurrencyId());
            creditCost(other.getCreditCost());
            unitValue(other.getUnitValue());
            billingFrequency(other.getBillingFrequency());
            billingFrequencyCustomMonths(other.getBillingFrequencyCustomMonths());
            billingType(other.getBillingType());
            pricePoints(other.getPricePoints());
            return this;
        }

        @java.lang.Override
        @JsonSetter("eventName")
        public CreditsCurrencyIdStage eventName(@NotNull String eventName) {
            this.eventName = Objects.requireNonNull(eventName, "eventName must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("creditsCurrencyId")
        public CreditCostStage creditsCurrencyId(@NotNull String creditsCurrencyId) {
            this.creditsCurrencyId = Objects.requireNonNull(creditsCurrencyId, "creditsCurrencyId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("creditCost")
        public _FinalStage creditCost(double creditCost) {
            this.creditCost = creditCost;
            return this;
        }

        @java.lang.Override
        public _FinalStage pricePoints(List<SimplePricePoint> pricePoints) {
            this.pricePoints = Optional.ofNullable(pricePoints);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pricePoints", nulls = Nulls.SKIP)
        public _FinalStage pricePoints(Optional<List<SimplePricePoint>> pricePoints) {
            this.pricePoints = pricePoints;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingType(UsagePrepaidCreditsInputBillingType billingType) {
            this.billingType = Optional.ofNullable(billingType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingType", nulls = Nulls.SKIP)
        public _FinalStage billingType(Optional<UsagePrepaidCreditsInputBillingType> billingType) {
            this.billingType = billingType;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingFrequencyCustomMonths(Integer billingFrequencyCustomMonths) {
            this.billingFrequencyCustomMonths = Optional.ofNullable(billingFrequencyCustomMonths);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingFrequencyCustomMonths", nulls = Nulls.SKIP)
        public _FinalStage billingFrequencyCustomMonths(Optional<Integer> billingFrequencyCustomMonths) {
            this.billingFrequencyCustomMonths = billingFrequencyCustomMonths;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingFrequency(UsagePrepaidCreditsInputBillingFrequency billingFrequency) {
            this.billingFrequency = Optional.ofNullable(billingFrequency);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingFrequency", nulls = Nulls.SKIP)
        public _FinalStage billingFrequency(Optional<UsagePrepaidCreditsInputBillingFrequency> billingFrequency) {
            this.billingFrequency = billingFrequency;
            return this;
        }

        @java.lang.Override
        public _FinalStage unitValue(Double unitValue) {
            this.unitValue = Optional.ofNullable(unitValue);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "unitValue", nulls = Nulls.SKIP)
        public _FinalStage unitValue(Optional<Double> unitValue) {
            this.unitValue = unitValue;
            return this;
        }

        @java.lang.Override
        public UsagePrepaidCreditsInput build() {
            return new UsagePrepaidCreditsInput(
                    eventName,
                    creditsCurrencyId,
                    creditCost,
                    unitValue,
                    billingFrequency,
                    billingFrequencyCustomMonths,
                    billingType,
                    pricePoints,
                    additionalProperties);
        }
    }
}
