/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType.Builder.class)
public final class ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType {
    private final ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType type;

    private final String unit;

    private final String unitDisplay;

    private final Map<String, Object> additionalProperties;

    private ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType(
            ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType type,
            String unit,
            String unitDisplay,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.unit = unit;
        this.unitDisplay = unitDisplay;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType getType() {
        return type;
    }

    @JsonProperty("unit")
    public String getUnit() {
        return unit;
    }

    @JsonProperty("unit_display")
    public String getUnitDisplay() {
        return unitDisplay;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType
                && equalTo((ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType other) {
        return type.equals(other.type) && unit.equals(other.unit) && unitDisplay.equals(other.unitDisplay);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.unit, this.unitDisplay);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        UnitStage type(@NotNull ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType type);

        Builder from(ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType other);
    }

    public interface UnitStage {
        UnitDisplayStage unit(@NotNull String unit);
    }

    public interface UnitDisplayStage {
        _FinalStage unitDisplay(@NotNull String unitDisplay);
    }

    public interface _FinalStage {
        ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, UnitStage, UnitDisplayStage, _FinalStage {
        private ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType type;

        private String unit;

        private String unitDisplay;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType other) {
            type(other.getType());
            unit(other.getUnit());
            unitDisplay(other.getUnitDisplay());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public UnitStage type(
                @NotNull ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("unit")
        public UnitDisplayStage unit(@NotNull String unit) {
            this.unit = Objects.requireNonNull(unit, "unit must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("unit_display")
        public _FinalStage unitDisplay(@NotNull String unitDisplay) {
            this.unitDisplay = Objects.requireNonNull(unitDisplay, "unitDisplay must not be null");
            return this;
        }

        @java.lang.Override
        public ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType build() {
            return new ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType(
                    type, unit, unitDisplay, additionalProperties);
        }
    }
}
