/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValueMetricUnit.Builder.class)
public final class ValueMetricUnit {
    private final ValueMetricUnitType type;

    private final Optional<ValueMetricUnitDurationUnit> durationUnit;

    private final Optional<String> unit;

    private final Optional<String> unitDisplay;

    private final Map<String, Object> additionalProperties;

    private ValueMetricUnit(
            ValueMetricUnitType type,
            Optional<ValueMetricUnitDurationUnit> durationUnit,
            Optional<String> unit,
            Optional<String> unitDisplay,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.durationUnit = durationUnit;
        this.unit = unit;
        this.unitDisplay = unitDisplay;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return 'monetary' = already a currency amount; 'duration' = a length of time (set durationUnit); 'custom' = a user-defined unit (set unit + unitDisplay).
     */
    @JsonProperty("type")
    public ValueMetricUnitType getType() {
        return type;
    }

    /**
     * @return Duration only: the time unit measured.
     */
    @JsonProperty("durationUnit")
    public Optional<ValueMetricUnitDurationUnit> getDurationUnit() {
        return durationUnit;
    }

    /**
     * @return Custom only: the machine-readable unit name, e.g. 'tickets'.
     */
    @JsonProperty("unit")
    public Optional<String> getUnit() {
        return unit;
    }

    /**
     * @return Custom only: the customer-facing label shown on value receipts.
     */
    @JsonProperty("unitDisplay")
    public Optional<String> getUnitDisplay() {
        return unitDisplay;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValueMetricUnit && equalTo((ValueMetricUnit) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValueMetricUnit other) {
        return type.equals(other.type)
                && durationUnit.equals(other.durationUnit)
                && unit.equals(other.unit)
                && unitDisplay.equals(other.unitDisplay);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.durationUnit, this.unit, this.unitDisplay);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>'monetary' = already a currency amount; 'duration' = a length of time (set durationUnit); 'custom' = a user-defined unit (set unit + unitDisplay).</p>
         */
        _FinalStage type(@NotNull ValueMetricUnitType type);

        Builder from(ValueMetricUnit other);
    }

    public interface _FinalStage {
        ValueMetricUnit build();

        /**
         * <p>Duration only: the time unit measured.</p>
         */
        _FinalStage durationUnit(Optional<ValueMetricUnitDurationUnit> durationUnit);

        _FinalStage durationUnit(ValueMetricUnitDurationUnit durationUnit);

        /**
         * <p>Custom only: the machine-readable unit name, e.g. 'tickets'.</p>
         */
        _FinalStage unit(Optional<String> unit);

        _FinalStage unit(String unit);

        /**
         * <p>Custom only: the customer-facing label shown on value receipts.</p>
         */
        _FinalStage unitDisplay(Optional<String> unitDisplay);

        _FinalStage unitDisplay(String unitDisplay);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private ValueMetricUnitType type;

        private Optional<String> unitDisplay = Optional.empty();

        private Optional<String> unit = Optional.empty();

        private Optional<ValueMetricUnitDurationUnit> durationUnit = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValueMetricUnit other) {
            type(other.getType());
            durationUnit(other.getDurationUnit());
            unit(other.getUnit());
            unitDisplay(other.getUnitDisplay());
            return this;
        }

        /**
         * <p>'monetary' = already a currency amount; 'duration' = a length of time (set durationUnit); 'custom' = a user-defined unit (set unit + unitDisplay).</p>
         * <p>'monetary' = already a currency amount; 'duration' = a length of time (set durationUnit); 'custom' = a user-defined unit (set unit + unitDisplay).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull ValueMetricUnitType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Custom only: the customer-facing label shown on value receipts.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage unitDisplay(String unitDisplay) {
            this.unitDisplay = Optional.ofNullable(unitDisplay);
            return this;
        }

        /**
         * <p>Custom only: the customer-facing label shown on value receipts.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "unitDisplay", nulls = Nulls.SKIP)
        public _FinalStage unitDisplay(Optional<String> unitDisplay) {
            this.unitDisplay = unitDisplay;
            return this;
        }

        /**
         * <p>Custom only: the machine-readable unit name, e.g. 'tickets'.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage unit(String unit) {
            this.unit = Optional.ofNullable(unit);
            return this;
        }

        /**
         * <p>Custom only: the machine-readable unit name, e.g. 'tickets'.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "unit", nulls = Nulls.SKIP)
        public _FinalStage unit(Optional<String> unit) {
            this.unit = unit;
            return this;
        }

        /**
         * <p>Duration only: the time unit measured.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage durationUnit(ValueMetricUnitDurationUnit durationUnit) {
            this.durationUnit = Optional.ofNullable(durationUnit);
            return this;
        }

        /**
         * <p>Duration only: the time unit measured.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "durationUnit", nulls = Nulls.SKIP)
        public _FinalStage durationUnit(Optional<ValueMetricUnitDurationUnit> durationUnit) {
            this.durationUnit = durationUnit;
            return this;
        }

        @java.lang.Override
        public ValueMetricUnit build() {
            return new ValueMetricUnit(type, durationUnit, unit, unitDisplay, additionalProperties);
        }
    }
}
