/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ValueMetricFormulaVariableFormat {
    PERCENT("percent"),

    DURATION("duration");

    private final String value;

    ValueMetricFormulaVariableFormat(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
