/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
        builder =
                ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem
                        .Builder.class)
public final class ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem {
    private final String field;

    private final
    ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator operator;

    private final ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
            value;

    private final
    ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult result;

    private final Map<String, Object> additionalProperties;

    private ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem(
            String field,
            ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator
                    operator,
            ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
                    value,
            ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult
                    result,
            Map<String, Object> additionalProperties) {
        this.field = field;
        this.operator = operator;
        this.value = value;
        this.result = result;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("field")
    public String getField() {
        return field;
    }

    @JsonProperty("operator")
    public ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator
            getOperator() {
        return operator;
    }

    @JsonProperty("value")
    public ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
            getValue() {
        return value;
    }

    @JsonProperty("result")
    public ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult
            getResult() {
        return result;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other
                        instanceof
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem
                && equalTo(
                        (ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem)
                                other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(
            ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem other) {
        return field.equals(other.field)
                && operator.equals(other.operator)
                && value.equals(other.value)
                && result.equals(other.result);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.field, this.operator, this.value, this.result);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FieldStage builder() {
        return new Builder();
    }

    public interface FieldStage {
        OperatorStage field(@NotNull String field);

        Builder from(
                ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem
                        other);
    }

    public interface OperatorStage {
        ValueStage operator(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator
                                operator);
    }

    public interface ValueStage {
        ResultStage value(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
                                value);
    }

    public interface ResultStage {
        _FinalStage result(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult
                                result);
    }

    public interface _FinalStage {
        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FieldStage, OperatorStage, ValueStage, ResultStage, _FinalStage {
        private String field;

        private
        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator
                operator;

        private ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
                value;

        private ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult
                result;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(
                ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem
                        other) {
            field(other.getField());
            operator(other.getOperator());
            value(other.getValue());
            result(other.getResult());
            return this;
        }

        @java.lang.Override
        @JsonSetter("field")
        public OperatorStage field(@NotNull String field) {
            this.field = Objects.requireNonNull(field, "field must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("operator")
        public ValueStage operator(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemOperator
                                operator) {
            this.operator = Objects.requireNonNull(operator, "operator must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("value")
        public ResultStage value(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemValue
                                value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("result")
        public _FinalStage result(
                @NotNull
                        ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItemResult
                                result) {
            this.result = Objects.requireNonNull(result, "result must not be null");
            return this;
        }

        @java.lang.Override
        public ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem
                build() {
            return new ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversionConditionsItem(
                    field, operator, value, result, additionalProperties);
        }
    }
}
