/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValueMetricSummary.Builder.class)
public final class ValueMetricSummary {
    private final String slug;

    private final String name;

    private final Optional<String> category;

    private final ValueMetricUnit unit;

    private final Optional<String> description;

    private final Optional<String> archivedAt;

    private final Optional<ValueMetricSummaryMonetaryConversion> monetaryConversion;

    private final Map<String, Object> additionalProperties;

    private ValueMetricSummary(
            String slug,
            String name,
            Optional<String> category,
            ValueMetricUnit unit,
            Optional<String> description,
            Optional<String> archivedAt,
            Optional<ValueMetricSummaryMonetaryConversion> monetaryConversion,
            Map<String, Object> additionalProperties) {
        this.slug = slug;
        this.name = name;
        this.category = category;
        this.unit = unit;
        this.description = description;
        this.archivedAt = archivedAt;
        this.monetaryConversion = monetaryConversion;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("slug")
    public String getSlug() {
        return slug;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonIgnore
    public Optional<String> getCategory() {
        if (category == null) {
            return Optional.empty();
        }
        return category;
    }

    @JsonProperty("unit")
    public ValueMetricUnit getUnit() {
        return unit;
    }

    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    @JsonIgnore
    public Optional<String> getArchivedAt() {
        if (archivedAt == null) {
            return Optional.empty();
        }
        return archivedAt;
    }

    @JsonIgnore
    public Optional<ValueMetricSummaryMonetaryConversion> getMonetaryConversion() {
        if (monetaryConversion == null) {
            return Optional.empty();
        }
        return monetaryConversion;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("category")
    private Optional<String> _getCategory() {
        return category;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("archivedAt")
    private Optional<String> _getArchivedAt() {
        return archivedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("monetaryConversion")
    private Optional<ValueMetricSummaryMonetaryConversion> _getMonetaryConversion() {
        return monetaryConversion;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValueMetricSummary && equalTo((ValueMetricSummary) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValueMetricSummary other) {
        return slug.equals(other.slug)
                && name.equals(other.name)
                && category.equals(other.category)
                && unit.equals(other.unit)
                && description.equals(other.description)
                && archivedAt.equals(other.archivedAt)
                && monetaryConversion.equals(other.monetaryConversion);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.slug,
                this.name,
                this.category,
                this.unit,
                this.description,
                this.archivedAt,
                this.monetaryConversion);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SlugStage builder() {
        return new Builder();
    }

    public interface SlugStage {
        NameStage slug(@NotNull String slug);

        Builder from(ValueMetricSummary other);
    }

    public interface NameStage {
        UnitStage name(@NotNull String name);
    }

    public interface UnitStage {
        _FinalStage unit(@NotNull ValueMetricUnit unit);
    }

    public interface _FinalStage {
        ValueMetricSummary build();

        _FinalStage category(Optional<String> category);

        _FinalStage category(String category);

        _FinalStage category(Nullable<String> category);

        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        _FinalStage archivedAt(Optional<String> archivedAt);

        _FinalStage archivedAt(String archivedAt);

        _FinalStage archivedAt(Nullable<String> archivedAt);

        _FinalStage monetaryConversion(Optional<ValueMetricSummaryMonetaryConversion> monetaryConversion);

        _FinalStage monetaryConversion(ValueMetricSummaryMonetaryConversion monetaryConversion);

        _FinalStage monetaryConversion(Nullable<ValueMetricSummaryMonetaryConversion> monetaryConversion);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SlugStage, NameStage, UnitStage, _FinalStage {
        private String slug;

        private String name;

        private ValueMetricUnit unit;

        private Optional<ValueMetricSummaryMonetaryConversion> monetaryConversion = Optional.empty();

        private Optional<String> archivedAt = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> category = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValueMetricSummary other) {
            slug(other.getSlug());
            name(other.getName());
            category(other.getCategory());
            unit(other.getUnit());
            description(other.getDescription());
            archivedAt(other.getArchivedAt());
            monetaryConversion(other.getMonetaryConversion());
            return this;
        }

        @java.lang.Override
        @JsonSetter("slug")
        public NameStage slug(@NotNull String slug) {
            this.slug = Objects.requireNonNull(slug, "slug must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public UnitStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("unit")
        public _FinalStage unit(@NotNull ValueMetricUnit unit) {
            this.unit = Objects.requireNonNull(unit, "unit must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage monetaryConversion(Nullable<ValueMetricSummaryMonetaryConversion> monetaryConversion) {
            if (monetaryConversion.isNull()) {
                this.monetaryConversion = null;
            } else if (monetaryConversion.isEmpty()) {
                this.monetaryConversion = Optional.empty();
            } else {
                this.monetaryConversion = Optional.of(monetaryConversion.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage monetaryConversion(ValueMetricSummaryMonetaryConversion monetaryConversion) {
            this.monetaryConversion = Optional.ofNullable(monetaryConversion);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "monetaryConversion", nulls = Nulls.SKIP)
        public _FinalStage monetaryConversion(Optional<ValueMetricSummaryMonetaryConversion> monetaryConversion) {
            this.monetaryConversion = monetaryConversion;
            return this;
        }

        @java.lang.Override
        public _FinalStage archivedAt(Nullable<String> archivedAt) {
            if (archivedAt.isNull()) {
                this.archivedAt = null;
            } else if (archivedAt.isEmpty()) {
                this.archivedAt = Optional.empty();
            } else {
                this.archivedAt = Optional.of(archivedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage archivedAt(String archivedAt) {
            this.archivedAt = Optional.ofNullable(archivedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "archivedAt", nulls = Nulls.SKIP)
        public _FinalStage archivedAt(Optional<String> archivedAt) {
            this.archivedAt = archivedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public _FinalStage category(Nullable<String> category) {
            if (category.isNull()) {
                this.category = null;
            } else if (category.isEmpty()) {
                this.category = Optional.empty();
            } else {
                this.category = Optional.of(category.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage category(String category) {
            this.category = Optional.ofNullable(category);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "category", nulls = Nulls.SKIP)
        public _FinalStage category(Optional<String> category) {
            this.category = category;
            return this;
        }

        @java.lang.Override
        public ValueMetricSummary build() {
            return new ValueMetricSummary(
                    slug, name, category, unit, description, archivedAt, monetaryConversion, additionalProperties);
        }
    }
}
