/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.customviewsexperimental.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum UpdateCustomViewPeriodRequestPeriodKind {
    RELATIVE("relative"),

    ABSOLUTE("absolute");

    private final String value;

    UpdateCustomViewPeriodRequestPeriodKind(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
