/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.pricing.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import com.paid.api.types.CreditBenefitInput;
import com.paid.api.types.PricingInput;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdatePricingRequest.Builder.class)
public final class UpdatePricingRequest {
    private final PricingInput pricing;

    private final Optional<List<CreditBenefitInput>> creditBenefits;

    private final Map<String, Object> additionalProperties;

    private UpdatePricingRequest(
            PricingInput pricing,
            Optional<List<CreditBenefitInput>> creditBenefits,
            Map<String, Object> additionalProperties) {
        this.pricing = pricing;
        this.creditBenefits = creditBenefits;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("pricing")
    public PricingInput getPricing() {
        return pricing;
    }

    @JsonProperty("creditBenefits")
    public Optional<List<CreditBenefitInput>> getCreditBenefits() {
        return creditBenefits;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdatePricingRequest && equalTo((UpdatePricingRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdatePricingRequest other) {
        return pricing.equals(other.pricing) && creditBenefits.equals(other.creditBenefits);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pricing, this.creditBenefits);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PricingStage builder() {
        return new Builder();
    }

    public interface PricingStage {
        _FinalStage pricing(@NotNull PricingInput pricing);

        Builder from(UpdatePricingRequest other);
    }

    public interface _FinalStage {
        UpdatePricingRequest build();

        _FinalStage creditBenefits(Optional<List<CreditBenefitInput>> creditBenefits);

        _FinalStage creditBenefits(List<CreditBenefitInput> creditBenefits);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PricingStage, _FinalStage {
        private PricingInput pricing;

        private Optional<List<CreditBenefitInput>> creditBenefits = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdatePricingRequest other) {
            pricing(other.getPricing());
            creditBenefits(other.getCreditBenefits());
            return this;
        }

        @java.lang.Override
        @JsonSetter("pricing")
        public _FinalStage pricing(@NotNull PricingInput pricing) {
            this.pricing = Objects.requireNonNull(pricing, "pricing must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage creditBenefits(List<CreditBenefitInput> creditBenefits) {
            this.creditBenefits = Optional.ofNullable(creditBenefits);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "creditBenefits", nulls = Nulls.SKIP)
        public _FinalStage creditBenefits(Optional<List<CreditBenefitInput>> creditBenefits) {
            this.creditBenefits = creditBenefits;
            return this;
        }

        @java.lang.Override
        public UpdatePricingRequest build() {
            return new UpdatePricingRequest(pricing, creditBenefits, additionalProperties);
        }
    }
}
