/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class PaidApiException extends RuntimeException {
    public PaidApiException(String message) {
        super(message);
    }

    public PaidApiException(String message, Exception e) {
        super(message, e);
    }
}
