/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.orders.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.Nullable;
import com.paid.api.core.NullableNonemptyFilter;
import com.paid.api.core.ObjectMappers;
import com.paid.api.types.CreateOrderLineRequest;
import com.paid.api.types.OrderBillingFrequencyOverride;
import com.paid.api.types.OrderCreationState;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateOrderRequest.Builder.class)
public final class CreateOrderRequest {
    private final String customerId;

    private final Optional<String> billingCustomerId;

    private final Optional<List<String>> billingContactIds;

    private final Optional<String> name;

    private final Optional<OffsetDateTime> startDate;

    private final Optional<OffsetDateTime> endDate;

    private final Optional<Integer> subscriptionTerms;

    private final Optional<OrderCreationState> creationState;

    private final Optional<Integer> billingAnchor;

    private final Optional<String> paymentTerms;

    private final Optional<String> externalId;

    private final Optional<Map<String, Object>> metadata;

    private final Optional<String> currency;

    private final Optional<Boolean> autoPostInvoices;

    private final Optional<Boolean> autoSendBillingEmails;

    private final Optional<Boolean> autoSendPaymentEmails;

    private final Optional<List<CreateOrderLineRequest>> lines;

    private final Optional<OrderBillingFrequencyOverride> billingFrequencyOverride;

    private final Optional<String> purchaseOrderReference;

    private final Map<String, Object> additionalProperties;

    private CreateOrderRequest(
            String customerId,
            Optional<String> billingCustomerId,
            Optional<List<String>> billingContactIds,
            Optional<String> name,
            Optional<OffsetDateTime> startDate,
            Optional<OffsetDateTime> endDate,
            Optional<Integer> subscriptionTerms,
            Optional<OrderCreationState> creationState,
            Optional<Integer> billingAnchor,
            Optional<String> paymentTerms,
            Optional<String> externalId,
            Optional<Map<String, Object>> metadata,
            Optional<String> currency,
            Optional<Boolean> autoPostInvoices,
            Optional<Boolean> autoSendBillingEmails,
            Optional<Boolean> autoSendPaymentEmails,
            Optional<List<CreateOrderLineRequest>> lines,
            Optional<OrderBillingFrequencyOverride> billingFrequencyOverride,
            Optional<String> purchaseOrderReference,
            Map<String, Object> additionalProperties) {
        this.customerId = customerId;
        this.billingCustomerId = billingCustomerId;
        this.billingContactIds = billingContactIds;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.subscriptionTerms = subscriptionTerms;
        this.creationState = creationState;
        this.billingAnchor = billingAnchor;
        this.paymentTerms = paymentTerms;
        this.externalId = externalId;
        this.metadata = metadata;
        this.currency = currency;
        this.autoPostInvoices = autoPostInvoices;
        this.autoSendBillingEmails = autoSendBillingEmails;
        this.autoSendPaymentEmails = autoSendPaymentEmails;
        this.lines = lines;
        this.billingFrequencyOverride = billingFrequencyOverride;
        this.purchaseOrderReference = purchaseOrderReference;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("customerId")
    public String getCustomerId() {
        return customerId;
    }

    @JsonProperty("billingCustomerId")
    public Optional<String> getBillingCustomerId() {
        return billingCustomerId;
    }

    @JsonProperty("billingContactIds")
    public Optional<List<String>> getBillingContactIds() {
        return billingContactIds;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("startDate")
    public Optional<OffsetDateTime> getStartDate() {
        return startDate;
    }

    @JsonProperty("endDate")
    public Optional<OffsetDateTime> getEndDate() {
        return endDate;
    }

    @JsonProperty("subscriptionTerms")
    public Optional<Integer> getSubscriptionTerms() {
        return subscriptionTerms;
    }

    @JsonProperty("creationState")
    public Optional<OrderCreationState> getCreationState() {
        return creationState;
    }

    /**
     * @return Day of month for billing anchor (1-31). Defaults to start date day if not provided.
     */
    @JsonProperty("billingAnchor")
    public Optional<Integer> getBillingAnchor() {
        return billingAnchor;
    }

    @JsonProperty("paymentTerms")
    public Optional<String> getPaymentTerms() {
        return paymentTerms;
    }

    @JsonProperty("externalId")
    public Optional<String> getExternalId() {
        return externalId;
    }

    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    @JsonProperty("currency")
    public Optional<String> getCurrency() {
        return currency;
    }

    @JsonProperty("autoPostInvoices")
    public Optional<Boolean> getAutoPostInvoices() {
        return autoPostInvoices;
    }

    @JsonProperty("autoSendBillingEmails")
    public Optional<Boolean> getAutoSendBillingEmails() {
        return autoSendBillingEmails;
    }

    @JsonProperty("autoSendPaymentEmails")
    public Optional<Boolean> getAutoSendPaymentEmails() {
        return autoSendPaymentEmails;
    }

    @JsonProperty("lines")
    public Optional<List<CreateOrderLineRequest>> getLines() {
        return lines;
    }

    @JsonProperty("billingFrequencyOverride")
    public Optional<OrderBillingFrequencyOverride> getBillingFrequencyOverride() {
        return billingFrequencyOverride;
    }

    /**
     * @return Purchase order number printed on invoices generated from this order.
     */
    @JsonIgnore
    public Optional<String> getPurchaseOrderReference() {
        if (purchaseOrderReference == null) {
            return Optional.empty();
        }
        return purchaseOrderReference;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("purchaseOrderReference")
    private Optional<String> _getPurchaseOrderReference() {
        return purchaseOrderReference;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateOrderRequest && equalTo((CreateOrderRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateOrderRequest other) {
        return customerId.equals(other.customerId)
                && billingCustomerId.equals(other.billingCustomerId)
                && billingContactIds.equals(other.billingContactIds)
                && name.equals(other.name)
                && startDate.equals(other.startDate)
                && endDate.equals(other.endDate)
                && subscriptionTerms.equals(other.subscriptionTerms)
                && creationState.equals(other.creationState)
                && billingAnchor.equals(other.billingAnchor)
                && paymentTerms.equals(other.paymentTerms)
                && externalId.equals(other.externalId)
                && metadata.equals(other.metadata)
                && currency.equals(other.currency)
                && autoPostInvoices.equals(other.autoPostInvoices)
                && autoSendBillingEmails.equals(other.autoSendBillingEmails)
                && autoSendPaymentEmails.equals(other.autoSendPaymentEmails)
                && lines.equals(other.lines)
                && billingFrequencyOverride.equals(other.billingFrequencyOverride)
                && purchaseOrderReference.equals(other.purchaseOrderReference);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.customerId,
                this.billingCustomerId,
                this.billingContactIds,
                this.name,
                this.startDate,
                this.endDate,
                this.subscriptionTerms,
                this.creationState,
                this.billingAnchor,
                this.paymentTerms,
                this.externalId,
                this.metadata,
                this.currency,
                this.autoPostInvoices,
                this.autoSendBillingEmails,
                this.autoSendPaymentEmails,
                this.lines,
                this.billingFrequencyOverride,
                this.purchaseOrderReference);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CustomerIdStage builder() {
        return new Builder();
    }

    public interface CustomerIdStage {
        _FinalStage customerId(@NotNull String customerId);

        Builder from(CreateOrderRequest other);
    }

    public interface _FinalStage {
        CreateOrderRequest build();

        _FinalStage billingCustomerId(Optional<String> billingCustomerId);

        _FinalStage billingCustomerId(String billingCustomerId);

        _FinalStage billingContactIds(Optional<List<String>> billingContactIds);

        _FinalStage billingContactIds(List<String> billingContactIds);

        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage startDate(Optional<OffsetDateTime> startDate);

        _FinalStage startDate(OffsetDateTime startDate);

        _FinalStage endDate(Optional<OffsetDateTime> endDate);

        _FinalStage endDate(OffsetDateTime endDate);

        _FinalStage subscriptionTerms(Optional<Integer> subscriptionTerms);

        _FinalStage subscriptionTerms(Integer subscriptionTerms);

        _FinalStage creationState(Optional<OrderCreationState> creationState);

        _FinalStage creationState(OrderCreationState creationState);

        /**
         * <p>Day of month for billing anchor (1-31). Defaults to start date day if not provided.</p>
         */
        _FinalStage billingAnchor(Optional<Integer> billingAnchor);

        _FinalStage billingAnchor(Integer billingAnchor);

        _FinalStage paymentTerms(Optional<String> paymentTerms);

        _FinalStage paymentTerms(String paymentTerms);

        _FinalStage externalId(Optional<String> externalId);

        _FinalStage externalId(String externalId);

        _FinalStage metadata(Optional<Map<String, Object>> metadata);

        _FinalStage metadata(Map<String, Object> metadata);

        _FinalStage currency(Optional<String> currency);

        _FinalStage currency(String currency);

        _FinalStage autoPostInvoices(Optional<Boolean> autoPostInvoices);

        _FinalStage autoPostInvoices(Boolean autoPostInvoices);

        _FinalStage autoSendBillingEmails(Optional<Boolean> autoSendBillingEmails);

        _FinalStage autoSendBillingEmails(Boolean autoSendBillingEmails);

        _FinalStage autoSendPaymentEmails(Optional<Boolean> autoSendPaymentEmails);

        _FinalStage autoSendPaymentEmails(Boolean autoSendPaymentEmails);

        _FinalStage lines(Optional<List<CreateOrderLineRequest>> lines);

        _FinalStage lines(List<CreateOrderLineRequest> lines);

        _FinalStage billingFrequencyOverride(Optional<OrderBillingFrequencyOverride> billingFrequencyOverride);

        _FinalStage billingFrequencyOverride(OrderBillingFrequencyOverride billingFrequencyOverride);

        /**
         * <p>Purchase order number printed on invoices generated from this order.</p>
         */
        _FinalStage purchaseOrderReference(Optional<String> purchaseOrderReference);

        _FinalStage purchaseOrderReference(String purchaseOrderReference);

        _FinalStage purchaseOrderReference(Nullable<String> purchaseOrderReference);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CustomerIdStage, _FinalStage {
        private String customerId;

        private Optional<String> purchaseOrderReference = Optional.empty();

        private Optional<OrderBillingFrequencyOverride> billingFrequencyOverride = Optional.empty();

        private Optional<List<CreateOrderLineRequest>> lines = Optional.empty();

        private Optional<Boolean> autoSendPaymentEmails = Optional.empty();

        private Optional<Boolean> autoSendBillingEmails = Optional.empty();

        private Optional<Boolean> autoPostInvoices = Optional.empty();

        private Optional<String> currency = Optional.empty();

        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        private Optional<String> paymentTerms = Optional.empty();

        private Optional<Integer> billingAnchor = Optional.empty();

        private Optional<OrderCreationState> creationState = Optional.empty();

        private Optional<Integer> subscriptionTerms = Optional.empty();

        private Optional<OffsetDateTime> endDate = Optional.empty();

        private Optional<OffsetDateTime> startDate = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<List<String>> billingContactIds = Optional.empty();

        private Optional<String> billingCustomerId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateOrderRequest other) {
            customerId(other.getCustomerId());
            billingCustomerId(other.getBillingCustomerId());
            billingContactIds(other.getBillingContactIds());
            name(other.getName());
            startDate(other.getStartDate());
            endDate(other.getEndDate());
            subscriptionTerms(other.getSubscriptionTerms());
            creationState(other.getCreationState());
            billingAnchor(other.getBillingAnchor());
            paymentTerms(other.getPaymentTerms());
            externalId(other.getExternalId());
            metadata(other.getMetadata());
            currency(other.getCurrency());
            autoPostInvoices(other.getAutoPostInvoices());
            autoSendBillingEmails(other.getAutoSendBillingEmails());
            autoSendPaymentEmails(other.getAutoSendPaymentEmails());
            lines(other.getLines());
            billingFrequencyOverride(other.getBillingFrequencyOverride());
            purchaseOrderReference(other.getPurchaseOrderReference());
            return this;
        }

        @java.lang.Override
        @JsonSetter("customerId")
        public _FinalStage customerId(@NotNull String customerId) {
            this.customerId = Objects.requireNonNull(customerId, "customerId must not be null");
            return this;
        }

        /**
         * <p>Purchase order number printed on invoices generated from this order.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage purchaseOrderReference(Nullable<String> purchaseOrderReference) {
            if (purchaseOrderReference.isNull()) {
                this.purchaseOrderReference = null;
            } else if (purchaseOrderReference.isEmpty()) {
                this.purchaseOrderReference = Optional.empty();
            } else {
                this.purchaseOrderReference = Optional.of(purchaseOrderReference.get());
            }
            return this;
        }

        /**
         * <p>Purchase order number printed on invoices generated from this order.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage purchaseOrderReference(String purchaseOrderReference) {
            this.purchaseOrderReference = Optional.ofNullable(purchaseOrderReference);
            return this;
        }

        /**
         * <p>Purchase order number printed on invoices generated from this order.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "purchaseOrderReference", nulls = Nulls.SKIP)
        public _FinalStage purchaseOrderReference(Optional<String> purchaseOrderReference) {
            this.purchaseOrderReference = purchaseOrderReference;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingFrequencyOverride(OrderBillingFrequencyOverride billingFrequencyOverride) {
            this.billingFrequencyOverride = Optional.ofNullable(billingFrequencyOverride);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingFrequencyOverride", nulls = Nulls.SKIP)
        public _FinalStage billingFrequencyOverride(Optional<OrderBillingFrequencyOverride> billingFrequencyOverride) {
            this.billingFrequencyOverride = billingFrequencyOverride;
            return this;
        }

        @java.lang.Override
        public _FinalStage lines(List<CreateOrderLineRequest> lines) {
            this.lines = Optional.ofNullable(lines);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "lines", nulls = Nulls.SKIP)
        public _FinalStage lines(Optional<List<CreateOrderLineRequest>> lines) {
            this.lines = lines;
            return this;
        }

        @java.lang.Override
        public _FinalStage autoSendPaymentEmails(Boolean autoSendPaymentEmails) {
            this.autoSendPaymentEmails = Optional.ofNullable(autoSendPaymentEmails);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "autoSendPaymentEmails", nulls = Nulls.SKIP)
        public _FinalStage autoSendPaymentEmails(Optional<Boolean> autoSendPaymentEmails) {
            this.autoSendPaymentEmails = autoSendPaymentEmails;
            return this;
        }

        @java.lang.Override
        public _FinalStage autoSendBillingEmails(Boolean autoSendBillingEmails) {
            this.autoSendBillingEmails = Optional.ofNullable(autoSendBillingEmails);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "autoSendBillingEmails", nulls = Nulls.SKIP)
        public _FinalStage autoSendBillingEmails(Optional<Boolean> autoSendBillingEmails) {
            this.autoSendBillingEmails = autoSendBillingEmails;
            return this;
        }

        @java.lang.Override
        public _FinalStage autoPostInvoices(Boolean autoPostInvoices) {
            this.autoPostInvoices = Optional.ofNullable(autoPostInvoices);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "autoPostInvoices", nulls = Nulls.SKIP)
        public _FinalStage autoPostInvoices(Optional<Boolean> autoPostInvoices) {
            this.autoPostInvoices = autoPostInvoices;
            return this;
        }

        @java.lang.Override
        public _FinalStage currency(String currency) {
            this.currency = Optional.ofNullable(currency);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "currency", nulls = Nulls.SKIP)
        public _FinalStage currency(Optional<String> currency) {
            this.currency = currency;
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        @java.lang.Override
        public _FinalStage externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "externalId", nulls = Nulls.SKIP)
        public _FinalStage externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        @java.lang.Override
        public _FinalStage paymentTerms(String paymentTerms) {
            this.paymentTerms = Optional.ofNullable(paymentTerms);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "paymentTerms", nulls = Nulls.SKIP)
        public _FinalStage paymentTerms(Optional<String> paymentTerms) {
            this.paymentTerms = paymentTerms;
            return this;
        }

        /**
         * <p>Day of month for billing anchor (1-31). Defaults to start date day if not provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage billingAnchor(Integer billingAnchor) {
            this.billingAnchor = Optional.ofNullable(billingAnchor);
            return this;
        }

        /**
         * <p>Day of month for billing anchor (1-31). Defaults to start date day if not provided.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "billingAnchor", nulls = Nulls.SKIP)
        public _FinalStage billingAnchor(Optional<Integer> billingAnchor) {
            this.billingAnchor = billingAnchor;
            return this;
        }

        @java.lang.Override
        public _FinalStage creationState(OrderCreationState creationState) {
            this.creationState = Optional.ofNullable(creationState);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "creationState", nulls = Nulls.SKIP)
        public _FinalStage creationState(Optional<OrderCreationState> creationState) {
            this.creationState = creationState;
            return this;
        }

        @java.lang.Override
        public _FinalStage subscriptionTerms(Integer subscriptionTerms) {
            this.subscriptionTerms = Optional.ofNullable(subscriptionTerms);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "subscriptionTerms", nulls = Nulls.SKIP)
        public _FinalStage subscriptionTerms(Optional<Integer> subscriptionTerms) {
            this.subscriptionTerms = subscriptionTerms;
            return this;
        }

        @java.lang.Override
        public _FinalStage endDate(OffsetDateTime endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "endDate", nulls = Nulls.SKIP)
        public _FinalStage endDate(Optional<OffsetDateTime> endDate) {
            this.endDate = endDate;
            return this;
        }

        @java.lang.Override
        public _FinalStage startDate(OffsetDateTime startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "startDate", nulls = Nulls.SKIP)
        public _FinalStage startDate(Optional<OffsetDateTime> startDate) {
            this.startDate = startDate;
            return this;
        }

        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingContactIds(List<String> billingContactIds) {
            this.billingContactIds = Optional.ofNullable(billingContactIds);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingContactIds", nulls = Nulls.SKIP)
        public _FinalStage billingContactIds(Optional<List<String>> billingContactIds) {
            this.billingContactIds = billingContactIds;
            return this;
        }

        @java.lang.Override
        public _FinalStage billingCustomerId(String billingCustomerId) {
            this.billingCustomerId = Optional.ofNullable(billingCustomerId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "billingCustomerId", nulls = Nulls.SKIP)
        public _FinalStage billingCustomerId(Optional<String> billingCustomerId) {
            this.billingCustomerId = billingCustomerId;
            return this;
        }

        @java.lang.Override
        public CreateOrderRequest build() {
            return new CreateOrderRequest(
                    customerId,
                    billingCustomerId,
                    billingContactIds,
                    name,
                    startDate,
                    endDate,
                    subscriptionTerms,
                    creationState,
                    billingAnchor,
                    paymentTerms,
                    externalId,
                    metadata,
                    currency,
                    autoPostInvoices,
                    autoSendBillingEmails,
                    autoSendPaymentEmails,
                    lines,
                    billingFrequencyOverride,
                    purchaseOrderReference,
                    additionalProperties);
        }
    }
}
