/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.customers.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetCustomerUnitCapByExternalIdRequest.Builder.class)
public final class GetCustomerUnitCapByExternalIdRequest {
    private final Optional<String> creditsCurrencyId;

    private final Map<String, Object> additionalProperties;

    private GetCustomerUnitCapByExternalIdRequest(
            Optional<String> creditsCurrencyId, Map<String, Object> additionalProperties) {
        this.creditsCurrencyId = creditsCurrencyId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The credits currency to read. Omit it only when the organization has exactly one credits currency, which is then used; otherwise it is required.
     */
    @JsonProperty("creditsCurrencyId")
    public Optional<String> getCreditsCurrencyId() {
        return creditsCurrencyId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetCustomerUnitCapByExternalIdRequest
                && equalTo((GetCustomerUnitCapByExternalIdRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetCustomerUnitCapByExternalIdRequest other) {
        return creditsCurrencyId.equals(other.creditsCurrencyId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.creditsCurrencyId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> creditsCurrencyId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetCustomerUnitCapByExternalIdRequest other) {
            creditsCurrencyId(other.getCreditsCurrencyId());
            return this;
        }

        /**
         * <p>The credits currency to read. Omit it only when the organization has exactly one credits currency, which is then used; otherwise it is required.</p>
         */
        @JsonSetter(value = "creditsCurrencyId", nulls = Nulls.SKIP)
        public Builder creditsCurrencyId(Optional<String> creditsCurrencyId) {
            this.creditsCurrencyId = creditsCurrencyId;
            return this;
        }

        public Builder creditsCurrencyId(String creditsCurrencyId) {
            this.creditsCurrencyId = Optional.ofNullable(creditsCurrencyId);
            return this;
        }

        public GetCustomerUnitCapByExternalIdRequest build() {
            return new GetCustomerUnitCapByExternalIdRequest(creditsCurrencyId, additionalProperties);
        }
    }
}
