/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.pricing;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.paid.api.core.ClientOptions;
import com.paid.api.core.MediaTypes;
import com.paid.api.core.ObjectMappers;
import com.paid.api.core.PaidApiApiException;
import com.paid.api.core.PaidApiException;
import com.paid.api.core.PaidApiHttpResponse;
import com.paid.api.core.QueryStringMapper;
import com.paid.api.core.RequestOptions;
import com.paid.api.errors.BadRequestError;
import com.paid.api.errors.InternalServerError;
import com.paid.api.errors.NotFoundError;
import com.paid.api.resources.pricing.requests.GetPricingRequest;
import com.paid.api.resources.pricing.requests.ListPricingRequest;
import com.paid.api.resources.pricing.requests.UpdatePricingRequest;
import com.paid.api.types.ErrorResponse;
import com.paid.api.types.PricingListResponse;
import com.paid.api.types.PricingResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPricingClient {
    protected final ClientOptions clientOptions;

    public RawPricingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns pricing for all product attributes of a product. Each entry includes the attribute's pricing configuration and credit benefits.
     */
    public PaidApiHttpResponse<PricingListResponse> listPricing(ListPricingRequest request) {
        return listPricing(request, null);
    }

    /**
     * Returns pricing for all product attributes of a product. Each entry includes the attribute's pricing configuration and credit benefits.
     */
    public PaidApiHttpResponse<PricingListResponse> listPricing(
            ListPricingRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pricing");
        QueryStringMapper.addQueryParameter(httpUrl, "productId", request.getProductId(), false);
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), PricingListResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns pricing and credit benefits for a single product attribute.
     */
    public PaidApiHttpResponse<PricingResponse> getPricing(String productAttributeId) {
        return getPricing(productAttributeId, GetPricingRequest.builder().build());
    }

    /**
     * Returns pricing and credit benefits for a single product attribute.
     */
    public PaidApiHttpResponse<PricingResponse> getPricing(String productAttributeId, GetPricingRequest request) {
        return getPricing(productAttributeId, request, null);
    }

    /**
     * Returns pricing and credit benefits for a single product attribute.
     */
    public PaidApiHttpResponse<PricingResponse> getPricing(
            String productAttributeId, GetPricingRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pricing")
                .addPathSegment(productAttributeId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), PricingResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates pricing on an existing product attribute. If creditBenefits is provided, it fully replaces existing benefits. If omitted, existing benefits are preserved.
     */
    public PaidApiHttpResponse<PricingResponse> updatePricing(String productAttributeId, UpdatePricingRequest request) {
        return updatePricing(productAttributeId, request, null);
    }

    /**
     * Updates pricing on an existing product attribute. If creditBenefits is provided, it fully replaces existing benefits. If omitted, existing benefits are preserved.
     */
    public PaidApiHttpResponse<PricingResponse> updatePricing(
            String productAttributeId, UpdatePricingRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pricing")
                .addPathSegment(productAttributeId)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PaidApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PaidApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), PricingResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new PaidApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new PaidApiException("Network error executing HTTP request", e);
        }
    }
}
