/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.errors;

import com.paid.api.core.PaidApiApiException;
import com.paid.api.types.ErrorResponse;
import okhttp3.Response;

public final class InternalServerError extends PaidApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ErrorResponse body;

    public InternalServerError(ErrorResponse body) {
        super("InternalServerError", 500, body);
        this.body = body;
    }

    public InternalServerError(ErrorResponse body, Response rawResponse) {
        super("InternalServerError", 500, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ErrorResponse body() {
        return this.body;
    }
}
