/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api;

import com.paid.api.core.ClientOptions;
import com.paid.api.core.Suppliers;
import com.paid.api.resources.agents.AgentsClient;
import com.paid.api.resources.contacts.ContactsClient;
import com.paid.api.resources.customers.CustomersClient;
import com.paid.api.resources.orders.OrdersClient;
import com.paid.api.resources.usage.UsageClient;
import java.util.function.Supplier;

public class PaidApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<CustomersClient> customersClient;

    protected final Supplier<AgentsClient> agentsClient;

    protected final Supplier<ContactsClient> contactsClient;

    protected final Supplier<OrdersClient> ordersClient;

    protected final Supplier<UsageClient> usageClient;

    public PaidApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.customersClient = Suppliers.memoize(() -> new CustomersClient(clientOptions));
        this.agentsClient = Suppliers.memoize(() -> new AgentsClient(clientOptions));
        this.contactsClient = Suppliers.memoize(() -> new ContactsClient(clientOptions));
        this.ordersClient = Suppliers.memoize(() -> new OrdersClient(clientOptions));
        this.usageClient = Suppliers.memoize(() -> new UsageClient(clientOptions));
    }

    public CustomersClient customers() {
        return this.customersClient.get();
    }

    public AgentsClient agents() {
        return this.agentsClient.get();
    }

    public ContactsClient contacts() {
        return this.contactsClient.get();
    }

    public OrdersClient orders() {
        return this.ordersClient.get();
    }

    public UsageClient usage() {
        return this.usageClient.get();
    }

    public static PaidApiClientBuilder builder() {
        return new PaidApiClientBuilder();
    }
}
