/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.orders.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ListOrdersRequestCreationState {
    DRAFT("draft"),

    ACTIVE("active");

    private final String value;

    ListOrdersRequestCreationState(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
