/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.customviewsexperimental.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import com.paid.api.resources.customviewsexperimental.types.UpdateCustomViewPeriodRequestPeriod;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateCustomViewPeriodRequest.Builder.class)
public final class UpdateCustomViewPeriodRequest {
    private final UpdateCustomViewPeriodRequestPeriod period;

    private final Map<String, Object> additionalProperties;

    private UpdateCustomViewPeriodRequest(
            UpdateCustomViewPeriodRequestPeriod period, Map<String, Object> additionalProperties) {
        this.period = period;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Default date range for the view's queries. Use <code>{period_start:DateTime}</code> / <code>{period_end:DateTime}</code> placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).
     */
    @JsonProperty("period")
    public UpdateCustomViewPeriodRequestPeriod getPeriod() {
        return period;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateCustomViewPeriodRequest && equalTo((UpdateCustomViewPeriodRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateCustomViewPeriodRequest other) {
        return period.equals(other.period);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.period);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PeriodStage builder() {
        return new Builder();
    }

    public interface PeriodStage {
        /**
         * <p>Default date range for the view's queries. Use <code>{period_start:DateTime}</code> / <code>{period_end:DateTime}</code> placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).</p>
         */
        _FinalStage period(@NotNull UpdateCustomViewPeriodRequestPeriod period);

        Builder from(UpdateCustomViewPeriodRequest other);
    }

    public interface _FinalStage {
        UpdateCustomViewPeriodRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PeriodStage, _FinalStage {
        private UpdateCustomViewPeriodRequestPeriod period;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateCustomViewPeriodRequest other) {
            period(other.getPeriod());
            return this;
        }

        /**
         * <p>Default date range for the view's queries. Use <code>{period_start:DateTime}</code> / <code>{period_end:DateTime}</code> placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).</p>
         * <p>Default date range for the view's queries. Use <code>{period_start:DateTime}</code> / <code>{period_end:DateTime}</code> placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("period")
        public _FinalStage period(@NotNull UpdateCustomViewPeriodRequestPeriod period) {
            this.period = Objects.requireNonNull(period, "period must not be null");
            return this;
        }

        @java.lang.Override
        public UpdateCustomViewPeriodRequest build() {
            return new UpdateCustomViewPeriodRequest(period, additionalProperties);
        }
    }
}
