/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.paid.api.resources.signals.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.paid.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListSignalsRequest.Builder.class)
public final class ListSignalsRequest {
    private final Optional<Integer> limit;

    private final Optional<Integer> offset;

    private final Optional<String> signalName;

    private final Optional<String> customerId;

    private final Optional<String> externalCustomerId;

    private final Optional<String> productId;

    private final Optional<String> externalProductId;

    private final Optional<String> createdAtFrom;

    private final Optional<String> createdAtTo;

    private final Map<String, Object> additionalProperties;

    private ListSignalsRequest(
            Optional<Integer> limit,
            Optional<Integer> offset,
            Optional<String> signalName,
            Optional<String> customerId,
            Optional<String> externalCustomerId,
            Optional<String> productId,
            Optional<String> externalProductId,
            Optional<String> createdAtFrom,
            Optional<String> createdAtTo,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.offset = offset;
        this.signalName = signalName;
        this.customerId = customerId;
        this.externalCustomerId = externalCustomerId;
        this.productId = productId;
        this.externalProductId = externalProductId;
        this.createdAtFrom = createdAtFrom;
        this.createdAtTo = createdAtTo;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @JsonProperty("offset")
    public Optional<Integer> getOffset() {
        return offset;
    }

    /**
     * @return Filter by signal event name (exact match).
     */
    @JsonProperty("signalName")
    public Optional<String> getSignalName() {
        return signalName;
    }

    /**
     * @return Filter by the Paid customer ID the signal is attributed to.
     */
    @JsonProperty("customerId")
    public Optional<String> getCustomerId() {
        return customerId;
    }

    /**
     * @return Filter by your external customer ID. Aliases resolve to the attributed customer, and unresolved IDs match raw ingest data.
     */
    @JsonProperty("externalCustomerId")
    public Optional<String> getExternalCustomerId() {
        return externalCustomerId;
    }

    /**
     * @return Filter by the Paid product ID the signal is attributed to.
     */
    @JsonProperty("productId")
    public Optional<String> getProductId() {
        return productId;
    }

    /**
     * @return Filter by your external product ID.
     */
    @JsonProperty("externalProductId")
    public Optional<String> getExternalProductId() {
        return externalProductId;
    }

    /**
     * @return Only signals created on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.
     */
    @JsonProperty("createdAtFrom")
    public Optional<String> getCreatedAtFrom() {
        return createdAtFrom;
    }

    /**
     * @return Only signals created on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.
     */
    @JsonProperty("createdAtTo")
    public Optional<String> getCreatedAtTo() {
        return createdAtTo;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListSignalsRequest && equalTo((ListSignalsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListSignalsRequest other) {
        return limit.equals(other.limit)
                && offset.equals(other.offset)
                && signalName.equals(other.signalName)
                && customerId.equals(other.customerId)
                && externalCustomerId.equals(other.externalCustomerId)
                && productId.equals(other.productId)
                && externalProductId.equals(other.externalProductId)
                && createdAtFrom.equals(other.createdAtFrom)
                && createdAtTo.equals(other.createdAtTo);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.limit,
                this.offset,
                this.signalName,
                this.customerId,
                this.externalCustomerId,
                this.productId,
                this.externalProductId,
                this.createdAtFrom,
                this.createdAtTo);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> offset = Optional.empty();

        private Optional<String> signalName = Optional.empty();

        private Optional<String> customerId = Optional.empty();

        private Optional<String> externalCustomerId = Optional.empty();

        private Optional<String> productId = Optional.empty();

        private Optional<String> externalProductId = Optional.empty();

        private Optional<String> createdAtFrom = Optional.empty();

        private Optional<String> createdAtTo = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListSignalsRequest other) {
            limit(other.getLimit());
            offset(other.getOffset());
            signalName(other.getSignalName());
            customerId(other.getCustomerId());
            externalCustomerId(other.getExternalCustomerId());
            productId(other.getProductId());
            externalProductId(other.getExternalProductId());
            createdAtFrom(other.getCreatedAtFrom());
            createdAtTo(other.getCreatedAtTo());
            return this;
        }

        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Integer> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Integer offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        /**
         * <p>Filter by signal event name (exact match).</p>
         */
        @JsonSetter(value = "signalName", nulls = Nulls.SKIP)
        public Builder signalName(Optional<String> signalName) {
            this.signalName = signalName;
            return this;
        }

        public Builder signalName(String signalName) {
            this.signalName = Optional.ofNullable(signalName);
            return this;
        }

        /**
         * <p>Filter by the Paid customer ID the signal is attributed to.</p>
         */
        @JsonSetter(value = "customerId", nulls = Nulls.SKIP)
        public Builder customerId(Optional<String> customerId) {
            this.customerId = customerId;
            return this;
        }

        public Builder customerId(String customerId) {
            this.customerId = Optional.ofNullable(customerId);
            return this;
        }

        /**
         * <p>Filter by your external customer ID. Aliases resolve to the attributed customer, and unresolved IDs match raw ingest data.</p>
         */
        @JsonSetter(value = "externalCustomerId", nulls = Nulls.SKIP)
        public Builder externalCustomerId(Optional<String> externalCustomerId) {
            this.externalCustomerId = externalCustomerId;
            return this;
        }

        public Builder externalCustomerId(String externalCustomerId) {
            this.externalCustomerId = Optional.ofNullable(externalCustomerId);
            return this;
        }

        /**
         * <p>Filter by the Paid product ID the signal is attributed to.</p>
         */
        @JsonSetter(value = "productId", nulls = Nulls.SKIP)
        public Builder productId(Optional<String> productId) {
            this.productId = productId;
            return this;
        }

        public Builder productId(String productId) {
            this.productId = Optional.ofNullable(productId);
            return this;
        }

        /**
         * <p>Filter by your external product ID.</p>
         */
        @JsonSetter(value = "externalProductId", nulls = Nulls.SKIP)
        public Builder externalProductId(Optional<String> externalProductId) {
            this.externalProductId = externalProductId;
            return this;
        }

        public Builder externalProductId(String externalProductId) {
            this.externalProductId = Optional.ofNullable(externalProductId);
            return this;
        }

        /**
         * <p>Only signals created on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.</p>
         */
        @JsonSetter(value = "createdAtFrom", nulls = Nulls.SKIP)
        public Builder createdAtFrom(Optional<String> createdAtFrom) {
            this.createdAtFrom = createdAtFrom;
            return this;
        }

        public Builder createdAtFrom(String createdAtFrom) {
            this.createdAtFrom = Optional.ofNullable(createdAtFrom);
            return this;
        }

        /**
         * <p>Only signals created on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.</p>
         */
        @JsonSetter(value = "createdAtTo", nulls = Nulls.SKIP)
        public Builder createdAtTo(Optional<String> createdAtTo) {
            this.createdAtTo = createdAtTo;
            return this;
        }

        public Builder createdAtTo(String createdAtTo) {
            this.createdAtTo = Optional.ofNullable(createdAtTo);
            return this;
        }

        public ListSignalsRequest build() {
            return new ListSignalsRequest(
                    limit,
                    offset,
                    signalName,
                    customerId,
                    externalCustomerId,
                    productId,
                    externalProductId,
                    createdAtFrom,
                    createdAtTo,
                    additionalProperties);
        }
    }
}
